// **********************************************************************
// Parsed By KsfParser(4.0.0.1070), Generated By tools(20200627)
// KsfParser Maintained By <KSF> and tools Maintained By <superzheng>
// Generated from "BaseData.ksf" by Server Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var KsfStream = require("@ksf/stream");

var _hasOwnProperty = Object.prototype.hasOwnProperty;

var ksQuant = ksQuant || {};
module.exports.ksQuant = ksQuant;

ksQuant.TRADE_CALENDAR_SESSION_TYPE = {
    "TCST_OPEN" : 0,
    "TCST_CLOSE" : 1,
    "TCST_BEFORE_OPEN" : 2,
    "TCST_AFTER_CLOSE" : 3,
    "TCST_AFTER_OPEN" : 4,
    "TCST_BEFORE_CLOSE" : 5
};
ksQuant.TRADE_CALENDAR_SESSION_TYPE._classname = "ksQuant.TRADE_CALENDAR_SESSION_TYPE";
ksQuant.TRADE_CALENDAR_SESSION_TYPE._write = function(os, tag, val) { return os.writeInt32(tag, val); };
ksQuant.TRADE_CALENDAR_SESSION_TYPE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); };

ksQuant.Instrument = function() {
    this.id = "";
    this.name = "";
    this.origin_code = "";
    this.origin_name = "";
    this.e_type = 0;
    this.exchange = "";
    this.market = "";
    this.exchange_mic = "";
    this.exchange_market = "";
    this.currency = "";
    this.tplus = 0;
    this.is_standard = false;
    this.is_tradable = false;
    this.is_expired = false;
    this.is_set = false;
    this.list_date = 0;
    this.de_list_date = 0;
    this.set_code = "";
    this._classname = "ksQuant.Instrument";
};
ksQuant.Instrument._classname = "ksQuant.Instrument";
ksQuant.Instrument._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.Instrument._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.Instrument._readFrom = function (is) {
    var tmp = new ksQuant.Instrument;
    tmp.id = is.readString(0, false, "");
    tmp.name = is.readString(1, false, "");
    tmp.origin_code = is.readString(2, false, "");
    tmp.origin_name = is.readString(3, false, "");
    tmp.e_type = is.readInt32(4, false, 0);
    tmp.exchange = is.readString(5, false, "");
    tmp.market = is.readString(6, false, "");
    tmp.exchange_mic = is.readString(7, false, "");
    tmp.exchange_market = is.readString(8, false, "");
    tmp.currency = is.readString(9, false, "");
    tmp.tplus = is.readInt32(10, false, 0);
    tmp.is_standard = is.readBoolean(11, false, false);
    tmp.is_tradable = is.readBoolean(12, false, false);
    tmp.is_expired = is.readBoolean(13, false, false);
    tmp.is_set = is.readBoolean(14, false, false);
    tmp.list_date = is.readInt32(15, false, 0);
    tmp.de_list_date = is.readInt32(16, false, 0);
    tmp.set_code = is.readString(17, false, "");
    return tmp;
};
ksQuant.Instrument.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeString(1, this.name);
    os.writeString(2, this.origin_code);
    os.writeString(3, this.origin_name);
    os.writeInt32(4, this.e_type);
    os.writeString(5, this.exchange);
    os.writeString(6, this.market);
    os.writeString(7, this.exchange_mic);
    os.writeString(8, this.exchange_market);
    os.writeString(9, this.currency);
    os.writeInt32(10, this.tplus);
    os.writeBoolean(11, this.is_standard);
    os.writeBoolean(12, this.is_tradable);
    os.writeBoolean(13, this.is_expired);
    os.writeBoolean(14, this.is_set);
    os.writeInt32(15, this.list_date);
    os.writeInt32(16, this.de_list_date);
    os.writeString(17, this.set_code);
};
ksQuant.Instrument.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.Instrument.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.Instrument.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "name" : this.name,
        "origin_code" : this.origin_code,
        "origin_name" : this.origin_name,
        "e_type" : this.e_type,
        "exchange" : this.exchange,
        "market" : this.market,
        "exchange_mic" : this.exchange_mic,
        "exchange_market" : this.exchange_market,
        "currency" : this.currency,
        "tplus" : this.tplus,
        "is_standard" : this.is_standard,
        "is_tradable" : this.is_tradable,
        "is_expired" : this.is_expired,
        "is_set" : this.is_set,
        "list_date" : this.list_date,
        "de_list_date" : this.de_list_date,
        "set_code" : this.set_code
    };
};
ksQuant.Instrument.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "name") && (this.name = json.name);
    _hasOwnProperty.call(json, "origin_code") && (this.origin_code = json.origin_code);
    _hasOwnProperty.call(json, "origin_name") && (this.origin_name = json.origin_name);
    _hasOwnProperty.call(json, "e_type") && (this.e_type = json.e_type);
    _hasOwnProperty.call(json, "exchange") && (this.exchange = json.exchange);
    _hasOwnProperty.call(json, "market") && (this.market = json.market);
    _hasOwnProperty.call(json, "exchange_mic") && (this.exchange_mic = json.exchange_mic);
    _hasOwnProperty.call(json, "exchange_market") && (this.exchange_market = json.exchange_market);
    _hasOwnProperty.call(json, "currency") && (this.currency = json.currency);
    _hasOwnProperty.call(json, "tplus") && (this.tplus = json.tplus);
    _hasOwnProperty.call(json, "is_standard") && (this.is_standard = json.is_standard);
    _hasOwnProperty.call(json, "is_tradable") && (this.is_tradable = json.is_tradable);
    _hasOwnProperty.call(json, "is_expired") && (this.is_expired = json.is_expired);
    _hasOwnProperty.call(json, "is_set") && (this.is_set = json.is_set);
    _hasOwnProperty.call(json, "list_date") && (this.list_date = json.list_date);
    _hasOwnProperty.call(json, "de_list_date") && (this.de_list_date = json.de_list_date);
    _hasOwnProperty.call(json, "set_code") && (this.set_code = json.set_code);
    return this;
};
ksQuant.Instrument.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.Instrument.new = function () {
    return new ksQuant.Instrument();
};
ksQuant.Instrument.create = function (is) {
    return ksQuant.Instrument._readFrom(is);
};

ksQuant.InstrumentHistory = function() {
    this.inst = new ksQuant.Instrument;
    this.change_date = 0;
    this._classname = "ksQuant.InstrumentHistory";
};
ksQuant.InstrumentHistory._classname = "ksQuant.InstrumentHistory";
ksQuant.InstrumentHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.InstrumentHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.InstrumentHistory._readFrom = function (is) {
    var tmp = new ksQuant.InstrumentHistory;
    tmp.inst = is.readStruct(0, false, ksQuant.Instrument);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.InstrumentHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.inst);
    os.writeInt32(1, this.change_date);
};
ksQuant.InstrumentHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.InstrumentHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.InstrumentHistory.prototype.toObject = function() { 
    return {
        "inst" : this.inst.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.InstrumentHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst") && (this.inst.readFromObject(json.inst));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.InstrumentHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.InstrumentHistory.new = function () {
    return new ksQuant.InstrumentHistory();
};
ksQuant.InstrumentHistory.create = function (is) {
    return ksQuant.InstrumentHistory._readFrom(is);
};

ksQuant.MainInstrument = function() {
    this.inst_id = "";
    this.trade_day = 0;
    this._classname = "ksQuant.MainInstrument";
};
ksQuant.MainInstrument._classname = "ksQuant.MainInstrument";
ksQuant.MainInstrument._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.MainInstrument._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.MainInstrument._readFrom = function (is) {
    var tmp = new ksQuant.MainInstrument;
    tmp.inst_id = is.readString(0, false, "");
    tmp.trade_day = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.MainInstrument.prototype._writeTo = function (os) {
    os.writeString(0, this.inst_id);
    os.writeInt32(1, this.trade_day);
};
ksQuant.MainInstrument.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.MainInstrument.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.MainInstrument.prototype.toObject = function() { 
    return {
        "inst_id" : this.inst_id,
        "trade_day" : this.trade_day
    };
};
ksQuant.MainInstrument.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst_id") && (this.inst_id = json.inst_id);
    _hasOwnProperty.call(json, "trade_day") && (this.trade_day = json.trade_day);
    return this;
};
ksQuant.MainInstrument.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.MainInstrument.new = function () {
    return new ksQuant.MainInstrument();
};
ksQuant.MainInstrument.create = function (is) {
    return ksQuant.MainInstrument._readFrom(is);
};

ksQuant.MainInstrumentHistory = function() {
    this.product = "";
    this.change_date = 0;
    this.main_ins = new ksQuant.MainInstrument;
    this._classname = "ksQuant.MainInstrumentHistory";
};
ksQuant.MainInstrumentHistory._classname = "ksQuant.MainInstrumentHistory";
ksQuant.MainInstrumentHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.MainInstrumentHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.MainInstrumentHistory._readFrom = function (is) {
    var tmp = new ksQuant.MainInstrumentHistory;
    tmp.product = is.readString(0, false, "");
    tmp.change_date = is.readInt32(1, false, 0);
    tmp.main_ins = is.readStruct(2, false, ksQuant.MainInstrument);
    return tmp;
};
ksQuant.MainInstrumentHistory.prototype._writeTo = function (os) {
    os.writeString(0, this.product);
    os.writeInt32(1, this.change_date);
    os.writeStruct(2, this.main_ins);
};
ksQuant.MainInstrumentHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.MainInstrumentHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.MainInstrumentHistory.prototype.toObject = function() { 
    return {
        "product" : this.product,
        "change_date" : this.change_date,
        "main_ins" : this.main_ins.toObject()
    };
};
ksQuant.MainInstrumentHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "product") && (this.product = json.product);
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    _hasOwnProperty.call(json, "main_ins") && (this.main_ins.readFromObject(json.main_ins));
    return this;
};
ksQuant.MainInstrumentHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.MainInstrumentHistory.new = function () {
    return new ksQuant.MainInstrumentHistory();
};
ksQuant.MainInstrumentHistory.create = function (is) {
    return ksQuant.MainInstrumentHistory._readFrom(is);
};

ksQuant.ChinaStockInstrument = function() {
    this.id = "";
    this.lot_size = 0;
    this.tick_table = "";
    this.price_tick = 0;
    this.comm_ratio = 0;
    this.stamp_tax = 0;
    this.transfer_fee = 0;
    this.exchange_fee = 0;
    this.other = 0;
    this.mini_comm = 0;
    this._classname = "ksQuant.ChinaStockInstrument";
};
ksQuant.ChinaStockInstrument._classname = "ksQuant.ChinaStockInstrument";
ksQuant.ChinaStockInstrument._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ChinaStockInstrument._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ChinaStockInstrument._readFrom = function (is) {
    var tmp = new ksQuant.ChinaStockInstrument;
    tmp.id = is.readString(0, false, "");
    tmp.lot_size = is.readDouble(1, false, 0);
    tmp.tick_table = is.readString(2, false, "");
    tmp.price_tick = is.readDouble(3, false, 0);
    tmp.comm_ratio = is.readDouble(4, false, 0);
    tmp.stamp_tax = is.readDouble(5, false, 0);
    tmp.transfer_fee = is.readDouble(6, false, 0);
    tmp.exchange_fee = is.readDouble(7, false, 0);
    tmp.other = is.readDouble(8, false, 0);
    tmp.mini_comm = is.readDouble(9, false, 0);
    return tmp;
};
ksQuant.ChinaStockInstrument.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeDouble(1, this.lot_size);
    os.writeString(2, this.tick_table);
    os.writeDouble(3, this.price_tick);
    os.writeDouble(4, this.comm_ratio);
    os.writeDouble(5, this.stamp_tax);
    os.writeDouble(6, this.transfer_fee);
    os.writeDouble(7, this.exchange_fee);
    os.writeDouble(8, this.other);
    os.writeDouble(9, this.mini_comm);
};
ksQuant.ChinaStockInstrument.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ChinaStockInstrument.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ChinaStockInstrument.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "lot_size" : this.lot_size,
        "tick_table" : this.tick_table,
        "price_tick" : this.price_tick,
        "comm_ratio" : this.comm_ratio,
        "stamp_tax" : this.stamp_tax,
        "transfer_fee" : this.transfer_fee,
        "exchange_fee" : this.exchange_fee,
        "other" : this.other,
        "mini_comm" : this.mini_comm
    };
};
ksQuant.ChinaStockInstrument.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "lot_size") && (this.lot_size = json.lot_size);
    _hasOwnProperty.call(json, "tick_table") && (this.tick_table = json.tick_table);
    _hasOwnProperty.call(json, "price_tick") && (this.price_tick = json.price_tick);
    _hasOwnProperty.call(json, "comm_ratio") && (this.comm_ratio = json.comm_ratio);
    _hasOwnProperty.call(json, "stamp_tax") && (this.stamp_tax = json.stamp_tax);
    _hasOwnProperty.call(json, "transfer_fee") && (this.transfer_fee = json.transfer_fee);
    _hasOwnProperty.call(json, "exchange_fee") && (this.exchange_fee = json.exchange_fee);
    _hasOwnProperty.call(json, "other") && (this.other = json.other);
    _hasOwnProperty.call(json, "mini_comm") && (this.mini_comm = json.mini_comm);
    return this;
};
ksQuant.ChinaStockInstrument.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ChinaStockInstrument.new = function () {
    return new ksQuant.ChinaStockInstrument();
};
ksQuant.ChinaStockInstrument.create = function (is) {
    return ksQuant.ChinaStockInstrument._readFrom(is);
};

ksQuant.ChinaStockInstrumentHistory = function() {
    this.inst = new ksQuant.ChinaStockInstrument;
    this.change_date = 0;
    this._classname = "ksQuant.ChinaStockInstrumentHistory";
};
ksQuant.ChinaStockInstrumentHistory._classname = "ksQuant.ChinaStockInstrumentHistory";
ksQuant.ChinaStockInstrumentHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ChinaStockInstrumentHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ChinaStockInstrumentHistory._readFrom = function (is) {
    var tmp = new ksQuant.ChinaStockInstrumentHistory;
    tmp.inst = is.readStruct(0, false, ksQuant.ChinaStockInstrument);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.ChinaStockInstrumentHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.inst);
    os.writeInt32(1, this.change_date);
};
ksQuant.ChinaStockInstrumentHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ChinaStockInstrumentHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ChinaStockInstrumentHistory.prototype.toObject = function() { 
    return {
        "inst" : this.inst.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.ChinaStockInstrumentHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst") && (this.inst.readFromObject(json.inst));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.ChinaStockInstrumentHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ChinaStockInstrumentHistory.new = function () {
    return new ksQuant.ChinaStockInstrumentHistory();
};
ksQuant.ChinaStockInstrumentHistory.create = function (is) {
    return ksQuant.ChinaStockInstrumentHistory._readFrom(is);
};

ksQuant.ChinaFutureInstrument = function() {
    this.id = "";
    this.product_id = "";
    this.combination_type = "";
    this.max_market_order_vol = 0;
    this.min_market_order_vol = 0;
    this.max_limit_order_vol = 0;
    this.min_limit_order_vol = 0;
    this.long_margin_ratio = 0;
    this.short_margin_ratio = 0;
    this.comm_ratio = 0;
    this.deliv_year = 0;
    this.deliv_month = 0;
    this.start_deliv_date = 0;
    this.end_deliv_date = 0;
    this._classname = "ksQuant.ChinaFutureInstrument";
};
ksQuant.ChinaFutureInstrument._classname = "ksQuant.ChinaFutureInstrument";
ksQuant.ChinaFutureInstrument._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ChinaFutureInstrument._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ChinaFutureInstrument._readFrom = function (is) {
    var tmp = new ksQuant.ChinaFutureInstrument;
    tmp.id = is.readString(0, false, "");
    tmp.product_id = is.readString(1, false, "");
    tmp.combination_type = is.readString(2, false, "");
    tmp.max_market_order_vol = is.readInt64(3, false, 0);
    tmp.min_market_order_vol = is.readInt64(4, false, 0);
    tmp.max_limit_order_vol = is.readInt64(5, false, 0);
    tmp.min_limit_order_vol = is.readInt64(6, false, 0);
    tmp.long_margin_ratio = is.readDouble(7, false, 0);
    tmp.short_margin_ratio = is.readDouble(8, false, 0);
    tmp.comm_ratio = is.readDouble(9, false, 0);
    tmp.deliv_year = is.readInt32(13, false, 0);
    tmp.deliv_month = is.readInt32(14, false, 0);
    tmp.start_deliv_date = is.readInt32(15, false, 0);
    tmp.end_deliv_date = is.readInt32(16, false, 0);
    return tmp;
};
ksQuant.ChinaFutureInstrument.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeString(1, this.product_id);
    os.writeString(2, this.combination_type);
    os.writeInt64(3, this.max_market_order_vol);
    os.writeInt64(4, this.min_market_order_vol);
    os.writeInt64(5, this.max_limit_order_vol);
    os.writeInt64(6, this.min_limit_order_vol);
    os.writeDouble(7, this.long_margin_ratio);
    os.writeDouble(8, this.short_margin_ratio);
    os.writeDouble(9, this.comm_ratio);
    os.writeInt32(13, this.deliv_year);
    os.writeInt32(14, this.deliv_month);
    os.writeInt32(15, this.start_deliv_date);
    os.writeInt32(16, this.end_deliv_date);
};
ksQuant.ChinaFutureInstrument.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ChinaFutureInstrument.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ChinaFutureInstrument.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "product_id" : this.product_id,
        "combination_type" : this.combination_type,
        "max_market_order_vol" : this.max_market_order_vol,
        "min_market_order_vol" : this.min_market_order_vol,
        "max_limit_order_vol" : this.max_limit_order_vol,
        "min_limit_order_vol" : this.min_limit_order_vol,
        "long_margin_ratio" : this.long_margin_ratio,
        "short_margin_ratio" : this.short_margin_ratio,
        "comm_ratio" : this.comm_ratio,
        "deliv_year" : this.deliv_year,
        "deliv_month" : this.deliv_month,
        "start_deliv_date" : this.start_deliv_date,
        "end_deliv_date" : this.end_deliv_date
    };
};
ksQuant.ChinaFutureInstrument.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "product_id") && (this.product_id = json.product_id);
    _hasOwnProperty.call(json, "combination_type") && (this.combination_type = json.combination_type);
    _hasOwnProperty.call(json, "max_market_order_vol") && (this.max_market_order_vol = json.max_market_order_vol);
    _hasOwnProperty.call(json, "min_market_order_vol") && (this.min_market_order_vol = json.min_market_order_vol);
    _hasOwnProperty.call(json, "max_limit_order_vol") && (this.max_limit_order_vol = json.max_limit_order_vol);
    _hasOwnProperty.call(json, "min_limit_order_vol") && (this.min_limit_order_vol = json.min_limit_order_vol);
    _hasOwnProperty.call(json, "long_margin_ratio") && (this.long_margin_ratio = json.long_margin_ratio);
    _hasOwnProperty.call(json, "short_margin_ratio") && (this.short_margin_ratio = json.short_margin_ratio);
    _hasOwnProperty.call(json, "comm_ratio") && (this.comm_ratio = json.comm_ratio);
    _hasOwnProperty.call(json, "deliv_year") && (this.deliv_year = json.deliv_year);
    _hasOwnProperty.call(json, "deliv_month") && (this.deliv_month = json.deliv_month);
    _hasOwnProperty.call(json, "start_deliv_date") && (this.start_deliv_date = json.start_deliv_date);
    _hasOwnProperty.call(json, "end_deliv_date") && (this.end_deliv_date = json.end_deliv_date);
    return this;
};
ksQuant.ChinaFutureInstrument.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ChinaFutureInstrument.new = function () {
    return new ksQuant.ChinaFutureInstrument();
};
ksQuant.ChinaFutureInstrument.create = function (is) {
    return ksQuant.ChinaFutureInstrument._readFrom(is);
};

ksQuant.ChinaFutureInstrumentHistory = function() {
    this.inst = new ksQuant.ChinaFutureInstrument;
    this.change_date = 0;
    this._classname = "ksQuant.ChinaFutureInstrumentHistory";
};
ksQuant.ChinaFutureInstrumentHistory._classname = "ksQuant.ChinaFutureInstrumentHistory";
ksQuant.ChinaFutureInstrumentHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ChinaFutureInstrumentHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ChinaFutureInstrumentHistory._readFrom = function (is) {
    var tmp = new ksQuant.ChinaFutureInstrumentHistory;
    tmp.inst = is.readStruct(0, false, ksQuant.ChinaFutureInstrument);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.ChinaFutureInstrumentHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.inst);
    os.writeInt32(1, this.change_date);
};
ksQuant.ChinaFutureInstrumentHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ChinaFutureInstrumentHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ChinaFutureInstrumentHistory.prototype.toObject = function() { 
    return {
        "inst" : this.inst.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.ChinaFutureInstrumentHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst") && (this.inst.readFromObject(json.inst));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.ChinaFutureInstrumentHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ChinaFutureInstrumentHistory.new = function () {
    return new ksQuant.ChinaFutureInstrumentHistory();
};
ksQuant.ChinaFutureInstrumentHistory.create = function (is) {
    return ksQuant.ChinaFutureInstrumentHistory._readFrom(is);
};

ksQuant.ChinaOptionInstrument = function() {
    this.id = "";
    this.product_id = "";
    this.combination_type = "";
    this.max_market_order_vol = 0;
    this.min_market_order_vol = 0;
    this.max_limit_order_vol = 0;
    this.min_limit_order_vol = 0;
    this.long_margin_ratio = 0;
    this.short_margin_ratio = 0;
    this.comm_ratio = 0;
    this.deliv_year = 0;
    this.deliv_month = 0;
    this.start_deliv_date = 0;
    this.end_deliv_date = 0;
    this._classname = "ksQuant.ChinaOptionInstrument";
};
ksQuant.ChinaOptionInstrument._classname = "ksQuant.ChinaOptionInstrument";
ksQuant.ChinaOptionInstrument._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ChinaOptionInstrument._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ChinaOptionInstrument._readFrom = function (is) {
    var tmp = new ksQuant.ChinaOptionInstrument;
    tmp.id = is.readString(0, false, "");
    tmp.product_id = is.readString(1, false, "");
    tmp.combination_type = is.readString(2, false, "");
    tmp.max_market_order_vol = is.readInt64(3, false, 0);
    tmp.min_market_order_vol = is.readInt64(4, false, 0);
    tmp.max_limit_order_vol = is.readInt64(5, false, 0);
    tmp.min_limit_order_vol = is.readInt64(6, false, 0);
    tmp.long_margin_ratio = is.readDouble(7, false, 0);
    tmp.short_margin_ratio = is.readDouble(8, false, 0);
    tmp.comm_ratio = is.readDouble(9, false, 0);
    tmp.deliv_year = is.readInt32(13, false, 0);
    tmp.deliv_month = is.readInt32(14, false, 0);
    tmp.start_deliv_date = is.readInt32(15, false, 0);
    tmp.end_deliv_date = is.readInt32(16, false, 0);
    return tmp;
};
ksQuant.ChinaOptionInstrument.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeString(1, this.product_id);
    os.writeString(2, this.combination_type);
    os.writeInt64(3, this.max_market_order_vol);
    os.writeInt64(4, this.min_market_order_vol);
    os.writeInt64(5, this.max_limit_order_vol);
    os.writeInt64(6, this.min_limit_order_vol);
    os.writeDouble(7, this.long_margin_ratio);
    os.writeDouble(8, this.short_margin_ratio);
    os.writeDouble(9, this.comm_ratio);
    os.writeInt32(13, this.deliv_year);
    os.writeInt32(14, this.deliv_month);
    os.writeInt32(15, this.start_deliv_date);
    os.writeInt32(16, this.end_deliv_date);
};
ksQuant.ChinaOptionInstrument.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ChinaOptionInstrument.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ChinaOptionInstrument.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "product_id" : this.product_id,
        "combination_type" : this.combination_type,
        "max_market_order_vol" : this.max_market_order_vol,
        "min_market_order_vol" : this.min_market_order_vol,
        "max_limit_order_vol" : this.max_limit_order_vol,
        "min_limit_order_vol" : this.min_limit_order_vol,
        "long_margin_ratio" : this.long_margin_ratio,
        "short_margin_ratio" : this.short_margin_ratio,
        "comm_ratio" : this.comm_ratio,
        "deliv_year" : this.deliv_year,
        "deliv_month" : this.deliv_month,
        "start_deliv_date" : this.start_deliv_date,
        "end_deliv_date" : this.end_deliv_date
    };
};
ksQuant.ChinaOptionInstrument.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "product_id") && (this.product_id = json.product_id);
    _hasOwnProperty.call(json, "combination_type") && (this.combination_type = json.combination_type);
    _hasOwnProperty.call(json, "max_market_order_vol") && (this.max_market_order_vol = json.max_market_order_vol);
    _hasOwnProperty.call(json, "min_market_order_vol") && (this.min_market_order_vol = json.min_market_order_vol);
    _hasOwnProperty.call(json, "max_limit_order_vol") && (this.max_limit_order_vol = json.max_limit_order_vol);
    _hasOwnProperty.call(json, "min_limit_order_vol") && (this.min_limit_order_vol = json.min_limit_order_vol);
    _hasOwnProperty.call(json, "long_margin_ratio") && (this.long_margin_ratio = json.long_margin_ratio);
    _hasOwnProperty.call(json, "short_margin_ratio") && (this.short_margin_ratio = json.short_margin_ratio);
    _hasOwnProperty.call(json, "comm_ratio") && (this.comm_ratio = json.comm_ratio);
    _hasOwnProperty.call(json, "deliv_year") && (this.deliv_year = json.deliv_year);
    _hasOwnProperty.call(json, "deliv_month") && (this.deliv_month = json.deliv_month);
    _hasOwnProperty.call(json, "start_deliv_date") && (this.start_deliv_date = json.start_deliv_date);
    _hasOwnProperty.call(json, "end_deliv_date") && (this.end_deliv_date = json.end_deliv_date);
    return this;
};
ksQuant.ChinaOptionInstrument.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ChinaOptionInstrument.new = function () {
    return new ksQuant.ChinaOptionInstrument();
};
ksQuant.ChinaOptionInstrument.create = function (is) {
    return ksQuant.ChinaOptionInstrument._readFrom(is);
};

ksQuant.ChinaOptionInstrumentHistory = function() {
    this.inst = new ksQuant.ChinaOptionInstrument;
    this.change_date = 0;
    this._classname = "ksQuant.ChinaOptionInstrumentHistory";
};
ksQuant.ChinaOptionInstrumentHistory._classname = "ksQuant.ChinaOptionInstrumentHistory";
ksQuant.ChinaOptionInstrumentHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ChinaOptionInstrumentHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ChinaOptionInstrumentHistory._readFrom = function (is) {
    var tmp = new ksQuant.ChinaOptionInstrumentHistory;
    tmp.inst = is.readStruct(0, false, ksQuant.ChinaOptionInstrument);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.ChinaOptionInstrumentHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.inst);
    os.writeInt32(1, this.change_date);
};
ksQuant.ChinaOptionInstrumentHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ChinaOptionInstrumentHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ChinaOptionInstrumentHistory.prototype.toObject = function() { 
    return {
        "inst" : this.inst.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.ChinaOptionInstrumentHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst") && (this.inst.readFromObject(json.inst));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.ChinaOptionInstrumentHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ChinaOptionInstrumentHistory.new = function () {
    return new ksQuant.ChinaOptionInstrumentHistory();
};
ksQuant.ChinaOptionInstrumentHistory.create = function (is) {
    return ksQuant.ChinaOptionInstrumentHistory._readFrom(is);
};

ksQuant.ProductInstrument = function() {
    this.id = "";
    this.name = "";
    this.support_markets = new KsfStream.List(KsfStream.String);
    this.e_type = 0;
    this.night_trading = false;
    this.max_market_order_vol = 0;
    this.min_market_order_vol = 0;
    this.max_limit_order_vol = 0;
    this.min_limit_order_vol = 0;
    this.vol_multi = 0;
    this.price_tick = 0;
    this.long_margin_ratio = 0;
    this.short_margin_ratio = 0;
    this.comm_ratio = 0;
    this.comm_unit = 0;
    this.pos_type = "";
    this.pos_date_type = "";
    this._classname = "ksQuant.ProductInstrument";
};
ksQuant.ProductInstrument._classname = "ksQuant.ProductInstrument";
ksQuant.ProductInstrument._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ProductInstrument._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ProductInstrument._readFrom = function (is) {
    var tmp = new ksQuant.ProductInstrument;
    tmp.id = is.readString(0, false, "");
    tmp.name = is.readString(1, false, "");
    tmp.support_markets = is.readList(2, false, KsfStream.List(KsfStream.String));
    tmp.e_type = is.readInt32(3, false, 0);
    tmp.night_trading = is.readBoolean(4, false, false);
    tmp.max_market_order_vol = is.readInt64(5, false, 0);
    tmp.min_market_order_vol = is.readInt64(6, false, 0);
    tmp.max_limit_order_vol = is.readInt64(7, false, 0);
    tmp.min_limit_order_vol = is.readInt64(8, false, 0);
    tmp.vol_multi = is.readDouble(9, false, 0);
    tmp.price_tick = is.readDouble(10, false, 0);
    tmp.long_margin_ratio = is.readDouble(11, false, 0);
    tmp.short_margin_ratio = is.readDouble(12, false, 0);
    tmp.comm_ratio = is.readDouble(13, false, 0);
    tmp.comm_unit = is.readInt32(14, false, 0);
    tmp.pos_type = is.readString(15, false, "");
    tmp.pos_date_type = is.readString(16, false, "");
    return tmp;
};
ksQuant.ProductInstrument.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeString(1, this.name);
    os.writeList(2, this.support_markets);
    os.writeInt32(3, this.e_type);
    os.writeBoolean(4, this.night_trading);
    os.writeInt64(5, this.max_market_order_vol);
    os.writeInt64(6, this.min_market_order_vol);
    os.writeInt64(7, this.max_limit_order_vol);
    os.writeInt64(8, this.min_limit_order_vol);
    os.writeDouble(9, this.vol_multi);
    os.writeDouble(10, this.price_tick);
    os.writeDouble(11, this.long_margin_ratio);
    os.writeDouble(12, this.short_margin_ratio);
    os.writeDouble(13, this.comm_ratio);
    os.writeInt32(14, this.comm_unit);
    os.writeString(15, this.pos_type);
    os.writeString(16, this.pos_date_type);
};
ksQuant.ProductInstrument.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ProductInstrument.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ProductInstrument.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "name" : this.name,
        "support_markets" : this.support_markets.toObject(),
        "e_type" : this.e_type,
        "night_trading" : this.night_trading,
        "max_market_order_vol" : this.max_market_order_vol,
        "min_market_order_vol" : this.min_market_order_vol,
        "max_limit_order_vol" : this.max_limit_order_vol,
        "min_limit_order_vol" : this.min_limit_order_vol,
        "vol_multi" : this.vol_multi,
        "price_tick" : this.price_tick,
        "long_margin_ratio" : this.long_margin_ratio,
        "short_margin_ratio" : this.short_margin_ratio,
        "comm_ratio" : this.comm_ratio,
        "comm_unit" : this.comm_unit,
        "pos_type" : this.pos_type,
        "pos_date_type" : this.pos_date_type
    };
};
ksQuant.ProductInstrument.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "name") && (this.name = json.name);
    _hasOwnProperty.call(json, "support_markets") && (this.support_markets.readFromObject(json.support_markets));
    _hasOwnProperty.call(json, "e_type") && (this.e_type = json.e_type);
    _hasOwnProperty.call(json, "night_trading") && (this.night_trading = json.night_trading);
    _hasOwnProperty.call(json, "max_market_order_vol") && (this.max_market_order_vol = json.max_market_order_vol);
    _hasOwnProperty.call(json, "min_market_order_vol") && (this.min_market_order_vol = json.min_market_order_vol);
    _hasOwnProperty.call(json, "max_limit_order_vol") && (this.max_limit_order_vol = json.max_limit_order_vol);
    _hasOwnProperty.call(json, "min_limit_order_vol") && (this.min_limit_order_vol = json.min_limit_order_vol);
    _hasOwnProperty.call(json, "vol_multi") && (this.vol_multi = json.vol_multi);
    _hasOwnProperty.call(json, "price_tick") && (this.price_tick = json.price_tick);
    _hasOwnProperty.call(json, "long_margin_ratio") && (this.long_margin_ratio = json.long_margin_ratio);
    _hasOwnProperty.call(json, "short_margin_ratio") && (this.short_margin_ratio = json.short_margin_ratio);
    _hasOwnProperty.call(json, "comm_ratio") && (this.comm_ratio = json.comm_ratio);
    _hasOwnProperty.call(json, "comm_unit") && (this.comm_unit = json.comm_unit);
    _hasOwnProperty.call(json, "pos_type") && (this.pos_type = json.pos_type);
    _hasOwnProperty.call(json, "pos_date_type") && (this.pos_date_type = json.pos_date_type);
    return this;
};
ksQuant.ProductInstrument.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ProductInstrument.new = function () {
    return new ksQuant.ProductInstrument();
};
ksQuant.ProductInstrument.create = function (is) {
    return ksQuant.ProductInstrument._readFrom(is);
};

ksQuant.ProductInstrumentHistory = function() {
    this.inst = new ksQuant.ProductInstrument;
    this.change_date = 0;
    this._classname = "ksQuant.ProductInstrumentHistory";
};
ksQuant.ProductInstrumentHistory._classname = "ksQuant.ProductInstrumentHistory";
ksQuant.ProductInstrumentHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ProductInstrumentHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ProductInstrumentHistory._readFrom = function (is) {
    var tmp = new ksQuant.ProductInstrumentHistory;
    tmp.inst = is.readStruct(0, false, ksQuant.ProductInstrument);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.ProductInstrumentHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.inst);
    os.writeInt32(1, this.change_date);
};
ksQuant.ProductInstrumentHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ProductInstrumentHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ProductInstrumentHistory.prototype.toObject = function() { 
    return {
        "inst" : this.inst.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.ProductInstrumentHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst") && (this.inst.readFromObject(json.inst));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.ProductInstrumentHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ProductInstrumentHistory.new = function () {
    return new ksQuant.ProductInstrumentHistory();
};
ksQuant.ProductInstrumentHistory.create = function (is) {
    return ksQuant.ProductInstrumentHistory._readFrom(is);
};

ksQuant.Exchange = function() {
    this.id = "";
    this.mic = "";
    this.origin_code = "";
    this.region = "";
    this._classname = "ksQuant.Exchange";
};
ksQuant.Exchange._classname = "ksQuant.Exchange";
ksQuant.Exchange._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.Exchange._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.Exchange._readFrom = function (is) {
    var tmp = new ksQuant.Exchange;
    tmp.id = is.readString(0, false, "");
    tmp.mic = is.readString(1, false, "");
    tmp.origin_code = is.readString(2, false, "");
    tmp.region = is.readString(3, false, "");
    return tmp;
};
ksQuant.Exchange.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeString(1, this.mic);
    os.writeString(2, this.origin_code);
    os.writeString(3, this.region);
};
ksQuant.Exchange.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.Exchange.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.Exchange.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "mic" : this.mic,
        "origin_code" : this.origin_code,
        "region" : this.region
    };
};
ksQuant.Exchange.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "mic") && (this.mic = json.mic);
    _hasOwnProperty.call(json, "origin_code") && (this.origin_code = json.origin_code);
    _hasOwnProperty.call(json, "region") && (this.region = json.region);
    return this;
};
ksQuant.Exchange.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.Exchange.new = function () {
    return new ksQuant.Exchange();
};
ksQuant.Exchange.create = function (is) {
    return ksQuant.Exchange._readFrom(is);
};

ksQuant.ExchangeHistory = function() {
    this.exchange = new ksQuant.Exchange;
    this.change_date = 0;
    this._classname = "ksQuant.ExchangeHistory";
};
ksQuant.ExchangeHistory._classname = "ksQuant.ExchangeHistory";
ksQuant.ExchangeHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ExchangeHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ExchangeHistory._readFrom = function (is) {
    var tmp = new ksQuant.ExchangeHistory;
    tmp.exchange = is.readStruct(0, false, ksQuant.Exchange);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.ExchangeHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.exchange);
    os.writeInt32(1, this.change_date);
};
ksQuant.ExchangeHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ExchangeHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ExchangeHistory.prototype.toObject = function() { 
    return {
        "exchange" : this.exchange.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.ExchangeHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "exchange") && (this.exchange.readFromObject(json.exchange));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.ExchangeHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ExchangeHistory.new = function () {
    return new ksQuant.ExchangeHistory();
};
ksQuant.ExchangeHistory.create = function (is) {
    return ksQuant.ExchangeHistory._readFrom(is);
};

ksQuant.Market = function() {
    this.id = "";
    this.name = "";
    this._classname = "ksQuant.Market";
};
ksQuant.Market._classname = "ksQuant.Market";
ksQuant.Market._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.Market._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.Market._readFrom = function (is) {
    var tmp = new ksQuant.Market;
    tmp.id = is.readString(0, false, "");
    tmp.name = is.readString(1, false, "");
    return tmp;
};
ksQuant.Market.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeString(1, this.name);
};
ksQuant.Market.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.Market.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.Market.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "name" : this.name
    };
};
ksQuant.Market.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "name") && (this.name = json.name);
    return this;
};
ksQuant.Market.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.Market.new = function () {
    return new ksQuant.Market();
};
ksQuant.Market.create = function (is) {
    return ksQuant.Market._readFrom(is);
};

ksQuant.TradeDay = function() {
    this.date = 0;
    this.flag = 0;
    this._classname = "ksQuant.TradeDay";
};
ksQuant.TradeDay._classname = "ksQuant.TradeDay";
ksQuant.TradeDay._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.TradeDay._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.TradeDay._readFrom = function (is) {
    var tmp = new ksQuant.TradeDay;
    tmp.date = is.readInt32(0, false, 0);
    tmp.flag = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.TradeDay.prototype._writeTo = function (os) {
    os.writeInt32(0, this.date);
    os.writeInt32(1, this.flag);
};
ksQuant.TradeDay.prototype._equal = function (anItem) {
    return this.date === anItem.date;
};
ksQuant.TradeDay.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.TradeDay.prototype.toObject = function() { 
    return {
        "date" : this.date,
        "flag" : this.flag
    };
};
ksQuant.TradeDay.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "date") && (this.date = json.date);
    _hasOwnProperty.call(json, "flag") && (this.flag = json.flag);
    return this;
};
ksQuant.TradeDay.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.TradeDay.new = function () {
    return new ksQuant.TradeDay();
};
ksQuant.TradeDay.create = function (is) {
    return ksQuant.TradeDay._readFrom(is);
};

ksQuant.TradeCalendar = function() {
    this.market = "";
    this.all_day = new KsfStream.List(ksQuant.TradeDay);
    this._classname = "ksQuant.TradeCalendar";
};
ksQuant.TradeCalendar._classname = "ksQuant.TradeCalendar";
ksQuant.TradeCalendar._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.TradeCalendar._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.TradeCalendar._readFrom = function (is) {
    var tmp = new ksQuant.TradeCalendar;
    tmp.market = is.readString(0, false, "");
    tmp.all_day = is.readList(1, false, KsfStream.List(ksQuant.TradeDay));
    return tmp;
};
ksQuant.TradeCalendar.prototype._writeTo = function (os) {
    os.writeString(0, this.market);
    os.writeList(1, this.all_day);
};
ksQuant.TradeCalendar.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.TradeCalendar.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.TradeCalendar.prototype.toObject = function() { 
    return {
        "market" : this.market,
        "all_day" : this.all_day.toObject()
    };
};
ksQuant.TradeCalendar.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "market") && (this.market = json.market);
    _hasOwnProperty.call(json, "all_day") && (this.all_day.readFromObject(json.all_day));
    return this;
};
ksQuant.TradeCalendar.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.TradeCalendar.new = function () {
    return new ksQuant.TradeCalendar();
};
ksQuant.TradeCalendar.create = function (is) {
    return ksQuant.TradeCalendar._readFrom(is);
};

ksQuant.TimeSlot = function() {
    this.open_time = 0;
    this.close_time = 0;
    this.from_time = 0;
    this.to_time = 0;
    this.sequence = 0;
    this.flag_bits = 0;
    this.extends = new KsfStream.Map(KsfStream.String, KsfStream.String);
    this._classname = "ksQuant.TimeSlot";
};
ksQuant.TimeSlot._classname = "ksQuant.TimeSlot";
ksQuant.TimeSlot._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.TimeSlot._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.TimeSlot._readFrom = function (is) {
    var tmp = new ksQuant.TimeSlot;
    tmp.open_time = is.readInt64(0, false, 0);
    tmp.close_time = is.readInt64(1, false, 0);
    tmp.from_time = is.readInt64(2, false, 0);
    tmp.to_time = is.readInt64(3, false, 0);
    tmp.sequence = is.readInt32(4, false, 0);
    tmp.flag_bits = is.readUInt32(5, false, 0);
    tmp.extends = is.readMap(10, false, KsfStream.Map(KsfStream.String, KsfStream.String));
    return tmp;
};
ksQuant.TimeSlot.prototype._writeTo = function (os) {
    os.writeInt64(0, this.open_time);
    os.writeInt64(1, this.close_time);
    os.writeInt64(2, this.from_time);
    os.writeInt64(3, this.to_time);
    os.writeInt32(4, this.sequence);
    os.writeUInt32(5, this.flag_bits);
    os.writeMap(10, this.extends);
};
ksQuant.TimeSlot.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.TimeSlot.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.TimeSlot.prototype.toObject = function() { 
    return {
        "open_time" : this.open_time,
        "close_time" : this.close_time,
        "from_time" : this.from_time,
        "to_time" : this.to_time,
        "sequence" : this.sequence,
        "flag_bits" : this.flag_bits,
        "extends" : this.extends.toObject()
    };
};
ksQuant.TimeSlot.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "open_time") && (this.open_time = json.open_time);
    _hasOwnProperty.call(json, "close_time") && (this.close_time = json.close_time);
    _hasOwnProperty.call(json, "from_time") && (this.from_time = json.from_time);
    _hasOwnProperty.call(json, "to_time") && (this.to_time = json.to_time);
    _hasOwnProperty.call(json, "sequence") && (this.sequence = json.sequence);
    _hasOwnProperty.call(json, "flag_bits") && (this.flag_bits = json.flag_bits);
    _hasOwnProperty.call(json, "extends") && (this.extends.readFromObject(json.extends));
    return this;
};
ksQuant.TimeSlot.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.TimeSlot.new = function () {
    return new ksQuant.TimeSlot();
};
ksQuant.TimeSlot.create = function (is) {
    return ksQuant.TimeSlot._readFrom(is);
};

ksQuant.TradeTime = function() {
    this.inst_id = "";
    this.time_slot = new KsfStream.List(ksQuant.TimeSlot);
    this._classname = "ksQuant.TradeTime";
};
ksQuant.TradeTime._classname = "ksQuant.TradeTime";
ksQuant.TradeTime._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.TradeTime._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.TradeTime._readFrom = function (is) {
    var tmp = new ksQuant.TradeTime;
    tmp.inst_id = is.readString(0, false, "");
    tmp.time_slot = is.readList(1, false, KsfStream.List(ksQuant.TimeSlot));
    return tmp;
};
ksQuant.TradeTime.prototype._writeTo = function (os) {
    os.writeString(0, this.inst_id);
    os.writeList(1, this.time_slot);
};
ksQuant.TradeTime.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.TradeTime.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.TradeTime.prototype.toObject = function() { 
    return {
        "inst_id" : this.inst_id,
        "time_slot" : this.time_slot.toObject()
    };
};
ksQuant.TradeTime.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst_id") && (this.inst_id = json.inst_id);
    _hasOwnProperty.call(json, "time_slot") && (this.time_slot.readFromObject(json.time_slot));
    return this;
};
ksQuant.TradeTime.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.TradeTime.new = function () {
    return new ksQuant.TradeTime();
};
ksQuant.TradeTime.create = function (is) {
    return ksQuant.TradeTime._readFrom(is);
};

ksQuant.TradeTimeHistory = function() {
    this.trade_time = new ksQuant.TradeTime;
    this.change_date = 0;
    this._classname = "ksQuant.TradeTimeHistory";
};
ksQuant.TradeTimeHistory._classname = "ksQuant.TradeTimeHistory";
ksQuant.TradeTimeHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.TradeTimeHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.TradeTimeHistory._readFrom = function (is) {
    var tmp = new ksQuant.TradeTimeHistory;
    tmp.trade_time = is.readStruct(0, false, ksQuant.TradeTime);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.TradeTimeHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.trade_time);
    os.writeInt32(1, this.change_date);
};
ksQuant.TradeTimeHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.TradeTimeHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.TradeTimeHistory.prototype.toObject = function() { 
    return {
        "trade_time" : this.trade_time.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.TradeTimeHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "trade_time") && (this.trade_time.readFromObject(json.trade_time));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.TradeTimeHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.TradeTimeHistory.new = function () {
    return new ksQuant.TradeTimeHistory();
};
ksQuant.TradeTimeHistory.create = function (is) {
    return ksQuant.TradeTimeHistory._readFrom(is);
};

ksQuant.InstrumentTradeTime = function() {
    this.trade_time_his = new KsfStream.Map(KsfStream.String, KsfStream.List(ksQuant.TradeTimeHistory));
    this._classname = "ksQuant.InstrumentTradeTime";
};
ksQuant.InstrumentTradeTime._classname = "ksQuant.InstrumentTradeTime";
ksQuant.InstrumentTradeTime._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.InstrumentTradeTime._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.InstrumentTradeTime._readFrom = function (is) {
    var tmp = new ksQuant.InstrumentTradeTime;
    tmp.trade_time_his = is.readMap(0, false, KsfStream.Map(KsfStream.String, KsfStream.List(ksQuant.TradeTimeHistory)));
    return tmp;
};
ksQuant.InstrumentTradeTime.prototype._writeTo = function (os) {
    os.writeMap(0, this.trade_time_his);
};
ksQuant.InstrumentTradeTime.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.InstrumentTradeTime.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.InstrumentTradeTime.prototype.toObject = function() { 
    return {
        "trade_time_his" : this.trade_time_his.toObject()
    };
};
ksQuant.InstrumentTradeTime.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "trade_time_his") && (this.trade_time_his.readFromObject(json.trade_time_his));
    return this;
};
ksQuant.InstrumentTradeTime.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.InstrumentTradeTime.new = function () {
    return new ksQuant.InstrumentTradeTime();
};
ksQuant.InstrumentTradeTime.create = function (is) {
    return ksQuant.InstrumentTradeTime._readFrom(is);
};

ksQuant.Xrxd = function() {
    this.inst_id = "";
    this.ex_date = 0;
    this.regi_date = 0;
    this.regi_close_price = 0;
    this.div_cash = 0;
    this.div_share = 0;
    this.trab_share = 0;
    this.place_rate = 0;
    this.place_price = 0;
    this.ex_factor = 0;
    this.cuml_ex_factor = 0;
    this.ex_price = 0;
    this.ex_div_price = 0;
    this.publish_time = 0;
    this._classname = "ksQuant.Xrxd";
};
ksQuant.Xrxd._classname = "ksQuant.Xrxd";
ksQuant.Xrxd._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.Xrxd._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.Xrxd._readFrom = function (is) {
    var tmp = new ksQuant.Xrxd;
    tmp.inst_id = is.readString(0, false, "");
    tmp.ex_date = is.readInt32(1, false, 0);
    tmp.regi_date = is.readInt32(2, false, 0);
    tmp.regi_close_price = is.readDouble(3, false, 0);
    tmp.div_cash = is.readDouble(4, false, 0);
    tmp.div_share = is.readDouble(5, false, 0);
    tmp.trab_share = is.readDouble(6, false, 0);
    tmp.place_rate = is.readDouble(7, false, 0);
    tmp.place_price = is.readDouble(8, false, 0);
    tmp.ex_factor = is.readDouble(9, false, 0);
    tmp.cuml_ex_factor = is.readDouble(10, false, 0);
    tmp.ex_price = is.readDouble(11, false, 0);
    tmp.ex_div_price = is.readDouble(12, false, 0);
    tmp.publish_time = is.readInt64(13, false, 0);
    return tmp;
};
ksQuant.Xrxd.prototype._writeTo = function (os) {
    os.writeString(0, this.inst_id);
    os.writeInt32(1, this.ex_date);
    os.writeInt32(2, this.regi_date);
    os.writeDouble(3, this.regi_close_price);
    os.writeDouble(4, this.div_cash);
    os.writeDouble(5, this.div_share);
    os.writeDouble(6, this.trab_share);
    os.writeDouble(7, this.place_rate);
    os.writeDouble(8, this.place_price);
    os.writeDouble(9, this.ex_factor);
    os.writeDouble(10, this.cuml_ex_factor);
    os.writeDouble(11, this.ex_price);
    os.writeDouble(12, this.ex_div_price);
    os.writeInt64(13, this.publish_time);
};
ksQuant.Xrxd.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.Xrxd.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.Xrxd.prototype.toObject = function() { 
    return {
        "inst_id" : this.inst_id,
        "ex_date" : this.ex_date,
        "regi_date" : this.regi_date,
        "regi_close_price" : this.regi_close_price,
        "div_cash" : this.div_cash,
        "div_share" : this.div_share,
        "trab_share" : this.trab_share,
        "place_rate" : this.place_rate,
        "place_price" : this.place_price,
        "ex_factor" : this.ex_factor,
        "cuml_ex_factor" : this.cuml_ex_factor,
        "ex_price" : this.ex_price,
        "ex_div_price" : this.ex_div_price,
        "publish_time" : this.publish_time
    };
};
ksQuant.Xrxd.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst_id") && (this.inst_id = json.inst_id);
    _hasOwnProperty.call(json, "ex_date") && (this.ex_date = json.ex_date);
    _hasOwnProperty.call(json, "regi_date") && (this.regi_date = json.regi_date);
    _hasOwnProperty.call(json, "regi_close_price") && (this.regi_close_price = json.regi_close_price);
    _hasOwnProperty.call(json, "div_cash") && (this.div_cash = json.div_cash);
    _hasOwnProperty.call(json, "div_share") && (this.div_share = json.div_share);
    _hasOwnProperty.call(json, "trab_share") && (this.trab_share = json.trab_share);
    _hasOwnProperty.call(json, "place_rate") && (this.place_rate = json.place_rate);
    _hasOwnProperty.call(json, "place_price") && (this.place_price = json.place_price);
    _hasOwnProperty.call(json, "ex_factor") && (this.ex_factor = json.ex_factor);
    _hasOwnProperty.call(json, "cuml_ex_factor") && (this.cuml_ex_factor = json.cuml_ex_factor);
    _hasOwnProperty.call(json, "ex_price") && (this.ex_price = json.ex_price);
    _hasOwnProperty.call(json, "ex_div_price") && (this.ex_div_price = json.ex_div_price);
    _hasOwnProperty.call(json, "publish_time") && (this.publish_time = json.publish_time);
    return this;
};
ksQuant.Xrxd.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.Xrxd.new = function () {
    return new ksQuant.Xrxd();
};
ksQuant.Xrxd.create = function (is) {
    return ksQuant.Xrxd._readFrom(is);
};

ksQuant.IndexComponent = function() {
    this.id = "";
    this.parent_id = "";
    this.check_in = 0;
    this.check_out = 0;
    this._classname = "ksQuant.IndexComponent";
};
ksQuant.IndexComponent._classname = "ksQuant.IndexComponent";
ksQuant.IndexComponent._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.IndexComponent._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.IndexComponent._readFrom = function (is) {
    var tmp = new ksQuant.IndexComponent;
    tmp.id = is.readString(0, false, "");
    tmp.parent_id = is.readString(1, false, "");
    tmp.check_in = is.readInt32(2, false, 0);
    tmp.check_out = is.readInt32(3, false, 0);
    return tmp;
};
ksQuant.IndexComponent.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeString(1, this.parent_id);
    os.writeInt32(2, this.check_in);
    os.writeInt32(3, this.check_out);
};
ksQuant.IndexComponent.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.IndexComponent.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.IndexComponent.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "parent_id" : this.parent_id,
        "check_in" : this.check_in,
        "check_out" : this.check_out
    };
};
ksQuant.IndexComponent.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "parent_id") && (this.parent_id = json.parent_id);
    _hasOwnProperty.call(json, "check_in") && (this.check_in = json.check_in);
    _hasOwnProperty.call(json, "check_out") && (this.check_out = json.check_out);
    return this;
};
ksQuant.IndexComponent.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.IndexComponent.new = function () {
    return new ksQuant.IndexComponent();
};
ksQuant.IndexComponent.create = function (is) {
    return ksQuant.IndexComponent._readFrom(is);
};

ksQuant.IndexComponentHistory = function() {
    this.inst = new ksQuant.IndexComponent;
    this.change_date = 0;
    this._classname = "ksQuant.IndexComponentHistory";
};
ksQuant.IndexComponentHistory._classname = "ksQuant.IndexComponentHistory";
ksQuant.IndexComponentHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.IndexComponentHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.IndexComponentHistory._readFrom = function (is) {
    var tmp = new ksQuant.IndexComponentHistory;
    tmp.inst = is.readStruct(0, false, ksQuant.IndexComponent);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.IndexComponentHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.inst);
    os.writeInt32(1, this.change_date);
};
ksQuant.IndexComponentHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.IndexComponentHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.IndexComponentHistory.prototype.toObject = function() { 
    return {
        "inst" : this.inst.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.IndexComponentHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst") && (this.inst.readFromObject(json.inst));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.IndexComponentHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.IndexComponentHistory.new = function () {
    return new ksQuant.IndexComponentHistory();
};
ksQuant.IndexComponentHistory.create = function (is) {
    return ksQuant.IndexComponentHistory._readFrom(is);
};

ksQuant.SpecialFactor = function() {
    this.inst_id = "";
    this.factor_key = "";
    this.factol_val = "";
    this._classname = "ksQuant.SpecialFactor";
};
ksQuant.SpecialFactor._classname = "ksQuant.SpecialFactor";
ksQuant.SpecialFactor._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.SpecialFactor._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.SpecialFactor._readFrom = function (is) {
    var tmp = new ksQuant.SpecialFactor;
    tmp.inst_id = is.readString(0, false, "");
    tmp.factor_key = is.readString(1, false, "");
    tmp.factol_val = is.readString(2, false, "");
    return tmp;
};
ksQuant.SpecialFactor.prototype._writeTo = function (os) {
    os.writeString(0, this.inst_id);
    os.writeString(1, this.factor_key);
    os.writeString(2, this.factol_val);
};
ksQuant.SpecialFactor.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.SpecialFactor.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.SpecialFactor.prototype.toObject = function() { 
    return {
        "inst_id" : this.inst_id,
        "factor_key" : this.factor_key,
        "factol_val" : this.factol_val
    };
};
ksQuant.SpecialFactor.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst_id") && (this.inst_id = json.inst_id);
    _hasOwnProperty.call(json, "factor_key") && (this.factor_key = json.factor_key);
    _hasOwnProperty.call(json, "factol_val") && (this.factol_val = json.factol_val);
    return this;
};
ksQuant.SpecialFactor.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.SpecialFactor.new = function () {
    return new ksQuant.SpecialFactor();
};
ksQuant.SpecialFactor.create = function (is) {
    return ksQuant.SpecialFactor._readFrom(is);
};

ksQuant.SpecialFactorHistory = function() {
    this.sf = new ksQuant.SpecialFactor;
    this.change_date = 0;
    this._classname = "ksQuant.SpecialFactorHistory";
};
ksQuant.SpecialFactorHistory._classname = "ksQuant.SpecialFactorHistory";
ksQuant.SpecialFactorHistory._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.SpecialFactorHistory._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.SpecialFactorHistory._readFrom = function (is) {
    var tmp = new ksQuant.SpecialFactorHistory;
    tmp.sf = is.readStruct(0, false, ksQuant.SpecialFactor);
    tmp.change_date = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.SpecialFactorHistory.prototype._writeTo = function (os) {
    os.writeStruct(0, this.sf);
    os.writeInt32(1, this.change_date);
};
ksQuant.SpecialFactorHistory.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.SpecialFactorHistory.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.SpecialFactorHistory.prototype.toObject = function() { 
    return {
        "sf" : this.sf.toObject(),
        "change_date" : this.change_date
    };
};
ksQuant.SpecialFactorHistory.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "sf") && (this.sf.readFromObject(json.sf));
    _hasOwnProperty.call(json, "change_date") && (this.change_date = json.change_date);
    return this;
};
ksQuant.SpecialFactorHistory.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.SpecialFactorHistory.new = function () {
    return new ksQuant.SpecialFactorHistory();
};
ksQuant.SpecialFactorHistory.create = function (is) {
    return ksQuant.SpecialFactorHistory._readFrom(is);
};



