// **********************************************************************
// Parsed By KsfParser(4.0.0.1070), Generated By tools(20200627)
// KsfParser Maintained By <KSF> and tools Maintained By <superzheng>
// Generated from "Comm.ksf" by Client Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var KsfStream = require("@ksf/stream");
var _KSF_MODULE_A_ = require("./UserKsf.js");

var _hasOwnProperty = Object.prototype.hasOwnProperty;

var ksQuant = ksQuant || {};
module.exports.ksQuant = ksQuant;


ksQuant.ExchangeEventType = {
    "BEFORE_OPEN_MARKET" : 1,
    "AFTER_CLOSE_MARKET" : 2,
    "SETTLE" : 3
};
ksQuant.ExchangeEventType._classname = "ksQuant.ExchangeEventType";
ksQuant.ExchangeEventType._write = function(os, tag, val) { return os.writeInt32(tag, val); };
ksQuant.ExchangeEventType._read  = function(is, tag, def) { return is.readInt32(tag, true, def); };

ksQuant.Error = function() {
    this.code = 0;
    this.msg = "";
    this._classname = "ksQuant.Error";
};
ksQuant.Error._classname = "ksQuant.Error";
ksQuant.Error._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.Error._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.Error._readFrom = function (is) {
    var tmp = new ksQuant.Error;
    tmp.code = is.readInt32(0, false, 0);
    tmp.msg = is.readString(1, false, "");
    return tmp;
};
ksQuant.Error.prototype._writeTo = function (os) {
    os.writeInt32(0, this.code);
    os.writeString(1, this.msg);
};
ksQuant.Error.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.Error.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.Error.prototype.toObject = function() { 
    return {
        "code" : this.code,
        "msg" : this.msg
    };
};
ksQuant.Error.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "code") && (this.code = json.code);
    _hasOwnProperty.call(json, "msg") && (this.msg = json.msg);
    return this;
};
ksQuant.Error.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.Error.new = function () {
    return new ksQuant.Error();
};
ksQuant.Error.create = function (is) {
    return ksQuant.Error._readFrom(is);
};

ksQuant.Pagination = function() {
    this.offset = 0;
    this.page_size = 0;
    this.total_count = 0;
    this._classname = "ksQuant.Pagination";
};
ksQuant.Pagination._classname = "ksQuant.Pagination";
ksQuant.Pagination._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.Pagination._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.Pagination._readFrom = function (is) {
    var tmp = new ksQuant.Pagination;
    tmp.offset = is.readInt64(0, false, 0);
    tmp.page_size = is.readInt64(1, false, 0);
    tmp.total_count = is.readInt64(2, false, 0);
    return tmp;
};
ksQuant.Pagination.prototype._writeTo = function (os) {
    os.writeInt64(0, this.offset);
    os.writeInt64(1, this.page_size);
    os.writeInt64(2, this.total_count);
};
ksQuant.Pagination.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.Pagination.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.Pagination.prototype.toObject = function() { 
    return {
        "offset" : this.offset,
        "page_size" : this.page_size,
        "total_count" : this.total_count
    };
};
ksQuant.Pagination.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "offset") && (this.offset = json.offset);
    _hasOwnProperty.call(json, "page_size") && (this.page_size = json.page_size);
    _hasOwnProperty.call(json, "total_count") && (this.total_count = json.total_count);
    return this;
};
ksQuant.Pagination.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.Pagination.new = function () {
    return new ksQuant.Pagination();
};
ksQuant.Pagination.create = function (is) {
    return ksQuant.Pagination._readFrom(is);
};

ksQuant.CacheRecord = function() {
    this.table_name = "";
    this.cached = true;
    this.updating = true;
    this.cache_index = new KsfStream.List(KsfStream.String);
    this.level1 = "";
    this.level2 = "";
    this.level3 = "";
    this._classname = "ksQuant.CacheRecord";
};
ksQuant.CacheRecord._classname = "ksQuant.CacheRecord";
ksQuant.CacheRecord._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.CacheRecord._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.CacheRecord._readFrom = function (is) {
    var tmp = new ksQuant.CacheRecord;
    tmp.table_name = is.readString(0, false, "");
    tmp.cached = is.readBoolean(1, false, true);
    tmp.updating = is.readBoolean(2, false, true);
    tmp.cache_index = is.readList(3, false, KsfStream.List(KsfStream.String));
    tmp.level1 = is.readString(4, false, "");
    tmp.level2 = is.readString(5, false, "");
    tmp.level3 = is.readString(6, false, "");
    return tmp;
};
ksQuant.CacheRecord.prototype._writeTo = function (os) {
    os.writeString(0, this.table_name);
    os.writeBoolean(1, this.cached);
    os.writeBoolean(2, this.updating);
    os.writeList(3, this.cache_index);
    os.writeString(4, this.level1);
    os.writeString(5, this.level2);
    os.writeString(6, this.level3);
};
ksQuant.CacheRecord.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.CacheRecord.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.CacheRecord.prototype.toObject = function() { 
    return {
        "table_name" : this.table_name,
        "cached" : this.cached,
        "updating" : this.updating,
        "cache_index" : this.cache_index.toObject(),
        "level1" : this.level1,
        "level2" : this.level2,
        "level3" : this.level3
    };
};
ksQuant.CacheRecord.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "table_name") && (this.table_name = json.table_name);
    _hasOwnProperty.call(json, "cached") && (this.cached = json.cached);
    _hasOwnProperty.call(json, "updating") && (this.updating = json.updating);
    _hasOwnProperty.call(json, "cache_index") && (this.cache_index.readFromObject(json.cache_index));
    _hasOwnProperty.call(json, "level1") && (this.level1 = json.level1);
    _hasOwnProperty.call(json, "level2") && (this.level2 = json.level2);
    _hasOwnProperty.call(json, "level3") && (this.level3 = json.level3);
    return this;
};
ksQuant.CacheRecord.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.CacheRecord.new = function () {
    return new ksQuant.CacheRecord();
};
ksQuant.CacheRecord.create = function (is) {
    return ksQuant.CacheRecord._readFrom(is);
};

ksQuant.LoginReq = function() {
    this.client = new _KSF_MODULE_A_.ksQuant.ClientInfo;
    this.token = "";
    this.account_id = "";
    this.pre_front_id = "";
    this.pre_session_id = "";
    this.now_front_id = "";
    this.now_session_id = "";
    this.timestamp = 0;
    this._classname = "ksQuant.LoginReq";
};
ksQuant.LoginReq._classname = "ksQuant.LoginReq";
ksQuant.LoginReq._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.LoginReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.LoginReq._readFrom = function (is) {
    var tmp = new ksQuant.LoginReq;
    tmp.client = is.readStruct(0, false, _KSF_MODULE_A_.ksQuant.ClientInfo);
    tmp.token = is.readString(1, false, "");
    tmp.account_id = is.readString(2, false, "");
    tmp.pre_front_id = is.readString(3, false, "");
    tmp.pre_session_id = is.readString(4, false, "");
    tmp.now_front_id = is.readString(5, false, "");
    tmp.now_session_id = is.readString(6, false, "");
    tmp.timestamp = is.readInt64(7, false, 0);
    return tmp;
};
ksQuant.LoginReq.prototype._writeTo = function (os) {
    os.writeStruct(0, this.client);
    os.writeString(1, this.token);
    os.writeString(2, this.account_id);
    os.writeString(3, this.pre_front_id);
    os.writeString(4, this.pre_session_id);
    os.writeString(5, this.now_front_id);
    os.writeString(6, this.now_session_id);
    os.writeInt64(7, this.timestamp);
};
ksQuant.LoginReq.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.LoginReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.LoginReq.prototype.toObject = function() { 
    return {
        "client" : this.client.toObject(),
        "token" : this.token,
        "account_id" : this.account_id,
        "pre_front_id" : this.pre_front_id,
        "pre_session_id" : this.pre_session_id,
        "now_front_id" : this.now_front_id,
        "now_session_id" : this.now_session_id,
        "timestamp" : this.timestamp
    };
};
ksQuant.LoginReq.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "client") && (this.client.readFromObject(json.client));
    _hasOwnProperty.call(json, "token") && (this.token = json.token);
    _hasOwnProperty.call(json, "account_id") && (this.account_id = json.account_id);
    _hasOwnProperty.call(json, "pre_front_id") && (this.pre_front_id = json.pre_front_id);
    _hasOwnProperty.call(json, "pre_session_id") && (this.pre_session_id = json.pre_session_id);
    _hasOwnProperty.call(json, "now_front_id") && (this.now_front_id = json.now_front_id);
    _hasOwnProperty.call(json, "now_session_id") && (this.now_session_id = json.now_session_id);
    _hasOwnProperty.call(json, "timestamp") && (this.timestamp = json.timestamp);
    return this;
};
ksQuant.LoginReq.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.LoginReq.new = function () {
    return new ksQuant.LoginReq();
};
ksQuant.LoginReq.create = function (is) {
    return ksQuant.LoginReq._readFrom(is);
};

ksQuant.LoginRsp = function() {
    this.ret = new ksQuant.Error;
    this.front_id = "";
    this.session_id = "";
    this._classname = "ksQuant.LoginRsp";
};
ksQuant.LoginRsp._classname = "ksQuant.LoginRsp";
ksQuant.LoginRsp._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.LoginRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.LoginRsp._readFrom = function (is) {
    var tmp = new ksQuant.LoginRsp;
    tmp.ret = is.readStruct(0, false, ksQuant.Error);
    tmp.front_id = is.readString(1, false, "");
    tmp.session_id = is.readString(2, false, "");
    return tmp;
};
ksQuant.LoginRsp.prototype._writeTo = function (os) {
    os.writeStruct(0, this.ret);
    os.writeString(1, this.front_id);
    os.writeString(2, this.session_id);
};
ksQuant.LoginRsp.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.LoginRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.LoginRsp.prototype.toObject = function() { 
    return {
        "ret" : this.ret.toObject(),
        "front_id" : this.front_id,
        "session_id" : this.session_id
    };
};
ksQuant.LoginRsp.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "ret") && (this.ret.readFromObject(json.ret));
    _hasOwnProperty.call(json, "front_id") && (this.front_id = json.front_id);
    _hasOwnProperty.call(json, "session_id") && (this.session_id = json.session_id);
    return this;
};
ksQuant.LoginRsp.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.LoginRsp.new = function () {
    return new ksQuant.LoginRsp();
};
ksQuant.LoginRsp.create = function (is) {
    return ksQuant.LoginRsp._readFrom(is);
};

ksQuant.LogoutReq = function() {
    this.client = new _KSF_MODULE_A_.ksQuant.ClientInfo;
    this.token = "";
    this.account_id = "";
    this.front_id = "";
    this.session_id = "";
    this._classname = "ksQuant.LogoutReq";
};
ksQuant.LogoutReq._classname = "ksQuant.LogoutReq";
ksQuant.LogoutReq._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.LogoutReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.LogoutReq._readFrom = function (is) {
    var tmp = new ksQuant.LogoutReq;
    tmp.client = is.readStruct(0, false, _KSF_MODULE_A_.ksQuant.ClientInfo);
    tmp.token = is.readString(1, false, "");
    tmp.account_id = is.readString(2, false, "");
    tmp.front_id = is.readString(3, false, "");
    tmp.session_id = is.readString(4, false, "");
    return tmp;
};
ksQuant.LogoutReq.prototype._writeTo = function (os) {
    os.writeStruct(0, this.client);
    os.writeString(1, this.token);
    os.writeString(2, this.account_id);
    os.writeString(3, this.front_id);
    os.writeString(4, this.session_id);
};
ksQuant.LogoutReq.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.LogoutReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.LogoutReq.prototype.toObject = function() { 
    return {
        "client" : this.client.toObject(),
        "token" : this.token,
        "account_id" : this.account_id,
        "front_id" : this.front_id,
        "session_id" : this.session_id
    };
};
ksQuant.LogoutReq.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "client") && (this.client.readFromObject(json.client));
    _hasOwnProperty.call(json, "token") && (this.token = json.token);
    _hasOwnProperty.call(json, "account_id") && (this.account_id = json.account_id);
    _hasOwnProperty.call(json, "front_id") && (this.front_id = json.front_id);
    _hasOwnProperty.call(json, "session_id") && (this.session_id = json.session_id);
    return this;
};
ksQuant.LogoutReq.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.LogoutReq.new = function () {
    return new ksQuant.LogoutReq();
};
ksQuant.LogoutReq.create = function (is) {
    return ksQuant.LogoutReq._readFrom(is);
};

ksQuant.LogoutRsp = function() {
    this.ret = new ksQuant.Error;
    this.front_id = "";
    this.session_id = "";
    this._classname = "ksQuant.LogoutRsp";
};
ksQuant.LogoutRsp._classname = "ksQuant.LogoutRsp";
ksQuant.LogoutRsp._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.LogoutRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.LogoutRsp._readFrom = function (is) {
    var tmp = new ksQuant.LogoutRsp;
    tmp.ret = is.readStruct(0, false, ksQuant.Error);
    tmp.front_id = is.readString(1, false, "");
    tmp.session_id = is.readString(2, false, "");
    return tmp;
};
ksQuant.LogoutRsp.prototype._writeTo = function (os) {
    os.writeStruct(0, this.ret);
    os.writeString(1, this.front_id);
    os.writeString(2, this.session_id);
};
ksQuant.LogoutRsp.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.LogoutRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.LogoutRsp.prototype.toObject = function() { 
    return {
        "ret" : this.ret.toObject(),
        "front_id" : this.front_id,
        "session_id" : this.session_id
    };
};
ksQuant.LogoutRsp.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "ret") && (this.ret.readFromObject(json.ret));
    _hasOwnProperty.call(json, "front_id") && (this.front_id = json.front_id);
    _hasOwnProperty.call(json, "session_id") && (this.session_id = json.session_id);
    return this;
};
ksQuant.LogoutRsp.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.LogoutRsp.new = function () {
    return new ksQuant.LogoutRsp();
};
ksQuant.LogoutRsp.create = function (is) {
    return ksQuant.LogoutRsp._readFrom(is);
};

ksQuant.RunLog = function() {
    this.id = "";
    this.level = "";
    this.module_id = "";
    this.run_id = "";
    this.strategy_id = "";
    this.user_id = "";
    this.msg = "";
    this.timestamp = 0;
    this._classname = "ksQuant.RunLog";
};
ksQuant.RunLog._classname = "ksQuant.RunLog";
ksQuant.RunLog._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.RunLog._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.RunLog._readFrom = function (is) {
    var tmp = new ksQuant.RunLog;
    tmp.id = is.readString(0, true, "");
    tmp.level = is.readString(1, true, "");
    tmp.module_id = is.readString(2, true, "");
    tmp.run_id = is.readString(3, false, "");
    tmp.strategy_id = is.readString(4, false, "");
    tmp.user_id = is.readString(5, false, "");
    tmp.msg = is.readString(6, true, "");
    tmp.timestamp = is.readInt64(7, true, 0);
    return tmp;
};
ksQuant.RunLog.prototype._writeTo = function (os) {
    os.writeString(0, this.id);
    os.writeString(1, this.level);
    os.writeString(2, this.module_id);
    os.writeString(3, this.run_id);
    os.writeString(4, this.strategy_id);
    os.writeString(5, this.user_id);
    os.writeString(6, this.msg);
    os.writeInt64(7, this.timestamp);
};
ksQuant.RunLog.prototype._equal = function (anItem) {
    return this.id === anItem.id && 
        this.user_id === anItem.user_id && 
        this.run_id === anItem.run_id && 
        this.strategy_id === anItem.strategy_id;
};
ksQuant.RunLog.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.RunLog.prototype.toObject = function() { 
    return {
        "id" : this.id,
        "level" : this.level,
        "module_id" : this.module_id,
        "run_id" : this.run_id,
        "strategy_id" : this.strategy_id,
        "user_id" : this.user_id,
        "msg" : this.msg,
        "timestamp" : this.timestamp
    };
};
ksQuant.RunLog.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "id") && (this.id = json.id);
    _hasOwnProperty.call(json, "level") && (this.level = json.level);
    _hasOwnProperty.call(json, "module_id") && (this.module_id = json.module_id);
    _hasOwnProperty.call(json, "run_id") && (this.run_id = json.run_id);
    _hasOwnProperty.call(json, "strategy_id") && (this.strategy_id = json.strategy_id);
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "msg") && (this.msg = json.msg);
    _hasOwnProperty.call(json, "timestamp") && (this.timestamp = json.timestamp);
    return this;
};
ksQuant.RunLog.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.RunLog.new = function () {
    return new ksQuant.RunLog();
};
ksQuant.RunLog.create = function (is) {
    return ksQuant.RunLog._readFrom(is);
};

ksQuant.CreateTableChangeHis = function() {
    this.struct_name = "";
    this.create_sql = "";
    this.update = 0;
    this._classname = "ksQuant.CreateTableChangeHis";
};
ksQuant.CreateTableChangeHis._classname = "ksQuant.CreateTableChangeHis";
ksQuant.CreateTableChangeHis._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.CreateTableChangeHis._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.CreateTableChangeHis._readFrom = function (is) {
    var tmp = new ksQuant.CreateTableChangeHis;
    tmp.struct_name = is.readString(0, true, "");
    tmp.create_sql = is.readString(1, true, "");
    tmp.update = is.readInt64(2, true, 0);
    return tmp;
};
ksQuant.CreateTableChangeHis.prototype._writeTo = function (os) {
    os.writeString(0, this.struct_name);
    os.writeString(1, this.create_sql);
    os.writeInt64(2, this.update);
};
ksQuant.CreateTableChangeHis.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.CreateTableChangeHis.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.CreateTableChangeHis.prototype.toObject = function() { 
    return {
        "struct_name" : this.struct_name,
        "create_sql" : this.create_sql,
        "update" : this.update
    };
};
ksQuant.CreateTableChangeHis.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "struct_name") && (this.struct_name = json.struct_name);
    _hasOwnProperty.call(json, "create_sql") && (this.create_sql = json.create_sql);
    _hasOwnProperty.call(json, "update") && (this.update = json.update);
    return this;
};
ksQuant.CreateTableChangeHis.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.CreateTableChangeHis.new = function () {
    return new ksQuant.CreateTableChangeHis();
};
ksQuant.CreateTableChangeHis.create = function (is) {
    return ksQuant.CreateTableChangeHis._readFrom(is);
};


