// **********************************************************************
// Parsed By KsfParser(4.0.0.1070), Generated By tools(20200627)
// KsfParser Maintained By <KSF> and tools Maintained By <superzheng>
// Generated from "User.ksf" by Server Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var KsfStream = require("@ksf/stream");

var _hasOwnProperty = Object.prototype.hasOwnProperty;

var ksQuant = ksQuant || {};
module.exports.ksQuant = ksQuant;

ksQuant.eCalcType = {
    "ECT_NONE" : 0,
    "ECT_PLUS" : 1,
    "ECT_MULTIPLY" : 2,
    "ECT_ABS" : 3
};
ksQuant.eCalcType._classname = "ksQuant.eCalcType";
ksQuant.eCalcType._write = function(os, tag, val) { return os.writeInt32(tag, val); };
ksQuant.eCalcType._read  = function(is, tag, def) { return is.readInt32(tag, true, def); };

ksQuant.UserProfile = function() {
    this.user_id = "";
    this.nickname = "";
    this.realname = "";
    this.card_type = "";
    this.card_id = "";
    this.mail = "";
    this.tel_no = "";
    this.wechat = "";
    this.remark = "";
    this.individual_flag = "";
    this.extra_params = new KsfStream.Map(KsfStream.String, KsfStream.String);
    this._classname = "ksQuant.UserProfile";
};
ksQuant.UserProfile._classname = "ksQuant.UserProfile";
ksQuant.UserProfile._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.UserProfile._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.UserProfile._readFrom = function (is) {
    var tmp = new ksQuant.UserProfile;
    tmp.user_id = is.readString(0, false, "");
    tmp.nickname = is.readString(1, false, "");
    tmp.realname = is.readString(2, false, "");
    tmp.card_type = is.readString(3, false, "");
    tmp.card_id = is.readString(4, false, "");
    tmp.mail = is.readString(5, false, "");
    tmp.tel_no = is.readString(6, false, "");
    tmp.wechat = is.readString(7, false, "");
    tmp.remark = is.readString(8, false, "");
    tmp.individual_flag = is.readString(9, false, "");
    tmp.extra_params = is.readMap(10, false, KsfStream.Map(KsfStream.String, KsfStream.String));
    return tmp;
};
ksQuant.UserProfile.prototype._writeTo = function (os) {
    os.writeString(0, this.user_id);
    os.writeString(1, this.nickname);
    os.writeString(2, this.realname);
    os.writeString(3, this.card_type);
    os.writeString(4, this.card_id);
    os.writeString(5, this.mail);
    os.writeString(6, this.tel_no);
    os.writeString(7, this.wechat);
    os.writeString(8, this.remark);
    os.writeString(9, this.individual_flag);
    os.writeMap(10, this.extra_params);
};
ksQuant.UserProfile.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.UserProfile.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.UserProfile.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id,
        "nickname" : this.nickname,
        "realname" : this.realname,
        "card_type" : this.card_type,
        "card_id" : this.card_id,
        "mail" : this.mail,
        "tel_no" : this.tel_no,
        "wechat" : this.wechat,
        "remark" : this.remark,
        "individual_flag" : this.individual_flag,
        "extra_params" : this.extra_params.toObject()
    };
};
ksQuant.UserProfile.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "nickname") && (this.nickname = json.nickname);
    _hasOwnProperty.call(json, "realname") && (this.realname = json.realname);
    _hasOwnProperty.call(json, "card_type") && (this.card_type = json.card_type);
    _hasOwnProperty.call(json, "card_id") && (this.card_id = json.card_id);
    _hasOwnProperty.call(json, "mail") && (this.mail = json.mail);
    _hasOwnProperty.call(json, "tel_no") && (this.tel_no = json.tel_no);
    _hasOwnProperty.call(json, "wechat") && (this.wechat = json.wechat);
    _hasOwnProperty.call(json, "remark") && (this.remark = json.remark);
    _hasOwnProperty.call(json, "individual_flag") && (this.individual_flag = json.individual_flag);
    _hasOwnProperty.call(json, "extra_params") && (this.extra_params.readFromObject(json.extra_params));
    return this;
};
ksQuant.UserProfile.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.UserProfile.new = function () {
    return new ksQuant.UserProfile();
};
ksQuant.UserProfile.create = function (is) {
    return ksQuant.UserProfile._readFrom(is);
};

ksQuant.UserAuth = function() {
    this.user_id = "";
    this.token = "";
    this.salt = "";
    this.user_type = "";
    this.role_ids = new KsfStream.List(KsfStream.String);
    this.user_status = "";
    this.trade_accounts = new KsfStream.List(KsfStream.String);
    this.domain_id = "";
    this.mod_pass = false;
    this.reg_time = 0;
    this.company_id = "";
    this.extra_params = new KsfStream.Map(KsfStream.String, KsfStream.String);
    this._classname = "ksQuant.UserAuth";
};
ksQuant.UserAuth._classname = "ksQuant.UserAuth";
ksQuant.UserAuth._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.UserAuth._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.UserAuth._readFrom = function (is) {
    var tmp = new ksQuant.UserAuth;
    tmp.user_id = is.readString(0, false, "");
    tmp.token = is.readString(1, false, "");
    tmp.salt = is.readString(2, false, "");
    tmp.user_type = is.readString(3, false, "");
    tmp.role_ids = is.readList(4, false, KsfStream.List(KsfStream.String));
    tmp.user_status = is.readString(5, false, "");
    tmp.trade_accounts = is.readList(6, false, KsfStream.List(KsfStream.String));
    tmp.domain_id = is.readString(7, false, "");
    tmp.mod_pass = is.readBoolean(8, false, false);
    tmp.reg_time = is.readInt64(9, false, 0);
    tmp.company_id = is.readString(10, false, "");
    tmp.extra_params = is.readMap(11, false, KsfStream.Map(KsfStream.String, KsfStream.String));
    return tmp;
};
ksQuant.UserAuth.prototype._writeTo = function (os) {
    os.writeString(0, this.user_id);
    os.writeString(1, this.token);
    os.writeString(2, this.salt);
    os.writeString(3, this.user_type);
    os.writeList(4, this.role_ids);
    os.writeString(5, this.user_status);
    os.writeList(6, this.trade_accounts);
    os.writeString(7, this.domain_id);
    os.writeBoolean(8, this.mod_pass);
    os.writeInt64(9, this.reg_time);
    os.writeString(10, this.company_id);
    os.writeMap(11, this.extra_params);
};
ksQuant.UserAuth.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.UserAuth.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.UserAuth.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id,
        "token" : this.token,
        "salt" : this.salt,
        "user_type" : this.user_type,
        "role_ids" : this.role_ids.toObject(),
        "user_status" : this.user_status,
        "trade_accounts" : this.trade_accounts.toObject(),
        "domain_id" : this.domain_id,
        "mod_pass" : this.mod_pass,
        "reg_time" : this.reg_time,
        "company_id" : this.company_id,
        "extra_params" : this.extra_params.toObject()
    };
};
ksQuant.UserAuth.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "token") && (this.token = json.token);
    _hasOwnProperty.call(json, "salt") && (this.salt = json.salt);
    _hasOwnProperty.call(json, "user_type") && (this.user_type = json.user_type);
    _hasOwnProperty.call(json, "role_ids") && (this.role_ids.readFromObject(json.role_ids));
    _hasOwnProperty.call(json, "user_status") && (this.user_status = json.user_status);
    _hasOwnProperty.call(json, "trade_accounts") && (this.trade_accounts.readFromObject(json.trade_accounts));
    _hasOwnProperty.call(json, "domain_id") && (this.domain_id = json.domain_id);
    _hasOwnProperty.call(json, "mod_pass") && (this.mod_pass = json.mod_pass);
    _hasOwnProperty.call(json, "reg_time") && (this.reg_time = json.reg_time);
    _hasOwnProperty.call(json, "company_id") && (this.company_id = json.company_id);
    _hasOwnProperty.call(json, "extra_params") && (this.extra_params.readFromObject(json.extra_params));
    return this;
};
ksQuant.UserAuth.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.UserAuth.new = function () {
    return new ksQuant.UserAuth();
};
ksQuant.UserAuth.create = function (is) {
    return ksQuant.UserAuth._readFrom(is);
};

ksQuant.UserPermission = function() {
    this.user_id = "";
    this.max_backtest = 0;
    this.max_simtrade = 0;
    this.max_realtime = 0;
    this._classname = "ksQuant.UserPermission";
};
ksQuant.UserPermission._classname = "ksQuant.UserPermission";
ksQuant.UserPermission._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.UserPermission._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.UserPermission._readFrom = function (is) {
    var tmp = new ksQuant.UserPermission;
    tmp.user_id = is.readString(0, false, "");
    tmp.max_backtest = is.readInt32(1, false, 0);
    tmp.max_simtrade = is.readInt32(2, false, 0);
    tmp.max_realtime = is.readInt32(3, false, 0);
    return tmp;
};
ksQuant.UserPermission.prototype._writeTo = function (os) {
    os.writeString(0, this.user_id);
    os.writeInt32(1, this.max_backtest);
    os.writeInt32(2, this.max_simtrade);
    os.writeInt32(3, this.max_realtime);
};
ksQuant.UserPermission.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.UserPermission.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.UserPermission.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id,
        "max_backtest" : this.max_backtest,
        "max_simtrade" : this.max_simtrade,
        "max_realtime" : this.max_realtime
    };
};
ksQuant.UserPermission.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "max_backtest") && (this.max_backtest = json.max_backtest);
    _hasOwnProperty.call(json, "max_simtrade") && (this.max_simtrade = json.max_simtrade);
    _hasOwnProperty.call(json, "max_realtime") && (this.max_realtime = json.max_realtime);
    return this;
};
ksQuant.UserPermission.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.UserPermission.new = function () {
    return new ksQuant.UserPermission();
};
ksQuant.UserPermission.create = function (is) {
    return ksQuant.UserPermission._readFrom(is);
};

ksQuant.UserDefinition = function() {
    this.user_id = "";
    this._classname = "ksQuant.UserDefinition";
};
ksQuant.UserDefinition._classname = "ksQuant.UserDefinition";
ksQuant.UserDefinition._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.UserDefinition._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.UserDefinition._readFrom = function (is) {
    var tmp = new ksQuant.UserDefinition;
    tmp.user_id = is.readString(0, false, "");
    return tmp;
};
ksQuant.UserDefinition.prototype._writeTo = function (os) {
    os.writeString(0, this.user_id);
};
ksQuant.UserDefinition.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.UserDefinition.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.UserDefinition.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id
    };
};
ksQuant.UserDefinition.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    return this;
};
ksQuant.UserDefinition.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.UserDefinition.new = function () {
    return new ksQuant.UserDefinition();
};
ksQuant.UserDefinition.create = function (is) {
    return ksQuant.UserDefinition._readFrom(is);
};

ksQuant.ClientInfo = function() {
    this.user_id = "";
    this.channel = "";
    this.guid = "";
    this.xua = "";
    this.imei = "";
    this.accounts = new KsfStream.List(KsfStream.String);
    this.macs = new KsfStream.List(KsfStream.String);
    this.hosts = new KsfStream.List(KsfStream.String);
    this.extra_params = new KsfStream.Map(KsfStream.String, KsfStream.String);
    this._classname = "ksQuant.ClientInfo";
};
ksQuant.ClientInfo._classname = "ksQuant.ClientInfo";
ksQuant.ClientInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ClientInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ClientInfo._readFrom = function (is) {
    var tmp = new ksQuant.ClientInfo;
    tmp.user_id = is.readString(0, false, "");
    tmp.channel = is.readString(1, false, "");
    tmp.guid = is.readString(2, false, "");
    tmp.xua = is.readString(3, false, "");
    tmp.imei = is.readString(4, false, "");
    tmp.accounts = is.readList(5, false, KsfStream.List(KsfStream.String));
    tmp.macs = is.readList(6, false, KsfStream.List(KsfStream.String));
    tmp.hosts = is.readList(7, false, KsfStream.List(KsfStream.String));
    tmp.extra_params = is.readMap(8, false, KsfStream.Map(KsfStream.String, KsfStream.String));
    return tmp;
};
ksQuant.ClientInfo.prototype._writeTo = function (os) {
    os.writeString(0, this.user_id);
    os.writeString(1, this.channel);
    os.writeString(2, this.guid);
    os.writeString(3, this.xua);
    os.writeString(4, this.imei);
    os.writeList(5, this.accounts);
    os.writeList(6, this.macs);
    os.writeList(7, this.hosts);
    os.writeMap(8, this.extra_params);
};
ksQuant.ClientInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ClientInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ClientInfo.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id,
        "channel" : this.channel,
        "guid" : this.guid,
        "xua" : this.xua,
        "imei" : this.imei,
        "accounts" : this.accounts.toObject(),
        "macs" : this.macs.toObject(),
        "hosts" : this.hosts.toObject(),
        "extra_params" : this.extra_params.toObject()
    };
};
ksQuant.ClientInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "channel") && (this.channel = json.channel);
    _hasOwnProperty.call(json, "guid") && (this.guid = json.guid);
    _hasOwnProperty.call(json, "xua") && (this.xua = json.xua);
    _hasOwnProperty.call(json, "imei") && (this.imei = json.imei);
    _hasOwnProperty.call(json, "accounts") && (this.accounts.readFromObject(json.accounts));
    _hasOwnProperty.call(json, "macs") && (this.macs.readFromObject(json.macs));
    _hasOwnProperty.call(json, "hosts") && (this.hosts.readFromObject(json.hosts));
    _hasOwnProperty.call(json, "extra_params") && (this.extra_params.readFromObject(json.extra_params));
    return this;
};
ksQuant.ClientInfo.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ClientInfo.new = function () {
    return new ksQuant.ClientInfo();
};
ksQuant.ClientInfo.create = function (is) {
    return ksQuant.ClientInfo._readFrom(is);
};

ksQuant.UserFeeCustom = function() {
    this.inst_id = "";
    this.calc_type = 0;
    this.value = 0;
    this._classname = "ksQuant.UserFeeCustom";
};
ksQuant.UserFeeCustom._classname = "ksQuant.UserFeeCustom";
ksQuant.UserFeeCustom._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.UserFeeCustom._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.UserFeeCustom._readFrom = function (is) {
    var tmp = new ksQuant.UserFeeCustom;
    tmp.inst_id = is.readString(0, false, "");
    tmp.calc_type = is.readInt32(1, false, 0);
    tmp.value = is.readDouble(2, false, 0);
    return tmp;
};
ksQuant.UserFeeCustom.prototype._writeTo = function (os) {
    os.writeString(0, this.inst_id);
    os.writeInt32(1, this.calc_type);
    os.writeDouble(2, this.value);
};
ksQuant.UserFeeCustom.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.UserFeeCustom.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.UserFeeCustom.prototype.toObject = function() { 
    return {
        "inst_id" : this.inst_id,
        "calc_type" : this.calc_type,
        "value" : this.value
    };
};
ksQuant.UserFeeCustom.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst_id") && (this.inst_id = json.inst_id);
    _hasOwnProperty.call(json, "calc_type") && (this.calc_type = json.calc_type);
    _hasOwnProperty.call(json, "value") && (this.value = json.value);
    return this;
};
ksQuant.UserFeeCustom.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.UserFeeCustom.new = function () {
    return new ksQuant.UserFeeCustom();
};
ksQuant.UserFeeCustom.create = function (is) {
    return ksQuant.UserFeeCustom._readFrom(is);
};

ksQuant.UserMarginRateCustom = function() {
    this.inst_id = "";
    this.calc_type = 0;
    this.value = 0;
    this._classname = "ksQuant.UserMarginRateCustom";
};
ksQuant.UserMarginRateCustom._classname = "ksQuant.UserMarginRateCustom";
ksQuant.UserMarginRateCustom._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.UserMarginRateCustom._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.UserMarginRateCustom._readFrom = function (is) {
    var tmp = new ksQuant.UserMarginRateCustom;
    tmp.inst_id = is.readString(0, false, "");
    tmp.calc_type = is.readInt32(1, false, 0);
    tmp.value = is.readDouble(2, false, 0);
    return tmp;
};
ksQuant.UserMarginRateCustom.prototype._writeTo = function (os) {
    os.writeString(0, this.inst_id);
    os.writeInt32(1, this.calc_type);
    os.writeDouble(2, this.value);
};
ksQuant.UserMarginRateCustom.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.UserMarginRateCustom.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.UserMarginRateCustom.prototype.toObject = function() { 
    return {
        "inst_id" : this.inst_id,
        "calc_type" : this.calc_type,
        "value" : this.value
    };
};
ksQuant.UserMarginRateCustom.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "inst_id") && (this.inst_id = json.inst_id);
    _hasOwnProperty.call(json, "calc_type") && (this.calc_type = json.calc_type);
    _hasOwnProperty.call(json, "value") && (this.value = json.value);
    return this;
};
ksQuant.UserMarginRateCustom.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.UserMarginRateCustom.new = function () {
    return new ksQuant.UserMarginRateCustom();
};
ksQuant.UserMarginRateCustom.create = function (is) {
    return ksQuant.UserMarginRateCustom._readFrom(is);
};

ksQuant.CustomConfig = function() {
    this.user_id = "";
    this.fee = new KsfStream.List(ksQuant.UserFeeCustom);
    this.margin_rate = new KsfStream.List(ksQuant.UserMarginRateCustom);
    this._classname = "ksQuant.CustomConfig";
};
ksQuant.CustomConfig._classname = "ksQuant.CustomConfig";
ksQuant.CustomConfig._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.CustomConfig._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.CustomConfig._readFrom = function (is) {
    var tmp = new ksQuant.CustomConfig;
    tmp.user_id = is.readString(0, false, "");
    tmp.fee = is.readList(1, false, KsfStream.List(ksQuant.UserFeeCustom));
    tmp.margin_rate = is.readList(2, false, KsfStream.List(ksQuant.UserMarginRateCustom));
    return tmp;
};
ksQuant.CustomConfig.prototype._writeTo = function (os) {
    os.writeString(0, this.user_id);
    os.writeList(1, this.fee);
    os.writeList(2, this.margin_rate);
};
ksQuant.CustomConfig.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.CustomConfig.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.CustomConfig.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id,
        "fee" : this.fee.toObject(),
        "margin_rate" : this.margin_rate.toObject()
    };
};
ksQuant.CustomConfig.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "fee") && (this.fee.readFromObject(json.fee));
    _hasOwnProperty.call(json, "margin_rate") && (this.margin_rate.readFromObject(json.margin_rate));
    return this;
};
ksQuant.CustomConfig.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.CustomConfig.new = function () {
    return new ksQuant.CustomConfig();
};
ksQuant.CustomConfig.create = function (is) {
    return ksQuant.CustomConfig._readFrom(is);
};

ksQuant.ConnectNode = function() {
    this.node_id = "";
    this.connects = new KsfStream.List(KsfStream.String);
    this._classname = "ksQuant.ConnectNode";
};
ksQuant.ConnectNode._classname = "ksQuant.ConnectNode";
ksQuant.ConnectNode._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ConnectNode._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ConnectNode._readFrom = function (is) {
    var tmp = new ksQuant.ConnectNode;
    tmp.node_id = is.readString(0, false, "");
    tmp.connects = is.readList(1, false, KsfStream.List(KsfStream.String));
    return tmp;
};
ksQuant.ConnectNode.prototype._writeTo = function (os) {
    os.writeString(0, this.node_id);
    os.writeList(1, this.connects);
};
ksQuant.ConnectNode.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ConnectNode.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ConnectNode.prototype.toObject = function() { 
    return {
        "node_id" : this.node_id,
        "connects" : this.connects.toObject()
    };
};
ksQuant.ConnectNode.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "node_id") && (this.node_id = json.node_id);
    _hasOwnProperty.call(json, "connects") && (this.connects.readFromObject(json.connects));
    return this;
};
ksQuant.ConnectNode.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ConnectNode.new = function () {
    return new ksQuant.ConnectNode();
};
ksQuant.ConnectNode.create = function (is) {
    return ksQuant.ConnectNode._readFrom(is);
};

ksQuant.ClientConnectNode = function() {
    this.user_id = "";
    this.nodes = new KsfStream.List(ksQuant.ConnectNode);
    this._classname = "ksQuant.ClientConnectNode";
};
ksQuant.ClientConnectNode._classname = "ksQuant.ClientConnectNode";
ksQuant.ClientConnectNode._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.ClientConnectNode._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.ClientConnectNode._readFrom = function (is) {
    var tmp = new ksQuant.ClientConnectNode;
    tmp.user_id = is.readString(0, false, "");
    tmp.nodes = is.readList(1, false, KsfStream.List(ksQuant.ConnectNode));
    return tmp;
};
ksQuant.ClientConnectNode.prototype._writeTo = function (os) {
    os.writeString(0, this.user_id);
    os.writeList(1, this.nodes);
};
ksQuant.ClientConnectNode.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.ClientConnectNode.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.ClientConnectNode.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id,
        "nodes" : this.nodes.toObject()
    };
};
ksQuant.ClientConnectNode.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "nodes") && (this.nodes.readFromObject(json.nodes));
    return this;
};
ksQuant.ClientConnectNode.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.ClientConnectNode.new = function () {
    return new ksQuant.ClientConnectNode();
};
ksQuant.ClientConnectNode.create = function (is) {
    return ksQuant.ClientConnectNode._readFrom(is);
};

ksQuant.EmailCaptcha = function() {
    this.captcha = "";
    this.create_time = 0;
    this._classname = "ksQuant.EmailCaptcha";
};
ksQuant.EmailCaptcha._classname = "ksQuant.EmailCaptcha";
ksQuant.EmailCaptcha._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.EmailCaptcha._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.EmailCaptcha._readFrom = function (is) {
    var tmp = new ksQuant.EmailCaptcha;
    tmp.captcha = is.readString(0, false, "");
    tmp.create_time = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.EmailCaptcha.prototype._writeTo = function (os) {
    os.writeString(0, this.captcha);
    os.writeInt32(1, this.create_time);
};
ksQuant.EmailCaptcha.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.EmailCaptcha.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.EmailCaptcha.prototype.toObject = function() { 
    return {
        "captcha" : this.captcha,
        "create_time" : this.create_time
    };
};
ksQuant.EmailCaptcha.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "captcha") && (this.captcha = json.captcha);
    _hasOwnProperty.call(json, "create_time") && (this.create_time = json.create_time);
    return this;
};
ksQuant.EmailCaptcha.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.EmailCaptcha.new = function () {
    return new ksQuant.EmailCaptcha();
};
ksQuant.EmailCaptcha.create = function (is) {
    return ksQuant.EmailCaptcha._readFrom(is);
};

ksQuant.UserModule = function() {
    this.user_id = 0;
    this.uni_key = 0;
    this._classname = "ksQuant.UserModule";
};
ksQuant.UserModule._classname = "ksQuant.UserModule";
ksQuant.UserModule._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.UserModule._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.UserModule._readFrom = function (is) {
    var tmp = new ksQuant.UserModule;
    tmp.user_id = is.readInt32(0, false, 0);
    tmp.uni_key = is.readInt32(1, false, 0);
    return tmp;
};
ksQuant.UserModule.prototype._writeTo = function (os) {
    os.writeInt32(0, this.user_id);
    os.writeInt32(1, this.uni_key);
};
ksQuant.UserModule.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.UserModule.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.UserModule.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id,
        "uni_key" : this.uni_key
    };
};
ksQuant.UserModule.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "uni_key") && (this.uni_key = json.uni_key);
    return this;
};
ksQuant.UserModule.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.UserModule.new = function () {
    return new ksQuant.UserModule();
};
ksQuant.UserModule.create = function (is) {
    return ksQuant.UserModule._readFrom(is);
};

ksQuant.User = function() {
    this.user_id = "";
    this.auth = new ksQuant.UserAuth;
    this.profile = new ksQuant.UserProfile;
    this.permission = new ksQuant.UserPermission;
    this.client = new ksQuant.ClientInfo;
    this.node = new ksQuant.ClientConnectNode;
    this.config = new ksQuant.CustomConfig;
    this.create = 0;
    this.update = 0;
    this._classname = "ksQuant.User";
};
ksQuant.User._classname = "ksQuant.User";
ksQuant.User._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.User._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.User._readFrom = function (is) {
    var tmp = new ksQuant.User;
    tmp.user_id = is.readString(0, false, "");
    tmp.auth = is.readStruct(1, false, ksQuant.UserAuth);
    tmp.profile = is.readStruct(2, false, ksQuant.UserProfile);
    tmp.permission = is.readStruct(3, false, ksQuant.UserPermission);
    tmp.client = is.readStruct(4, false, ksQuant.ClientInfo);
    tmp.node = is.readStruct(5, false, ksQuant.ClientConnectNode);
    tmp.config = is.readStruct(6, false, ksQuant.CustomConfig);
    tmp.create = is.readInt64(7, false, 0);
    tmp.update = is.readInt64(8, false, 0);
    return tmp;
};
ksQuant.User.prototype._writeTo = function (os) {
    os.writeString(0, this.user_id);
    os.writeStruct(1, this.auth);
    os.writeStruct(2, this.profile);
    os.writeStruct(3, this.permission);
    os.writeStruct(4, this.client);
    os.writeStruct(5, this.node);
    os.writeStruct(6, this.config);
    os.writeInt64(7, this.create);
    os.writeInt64(8, this.update);
};
ksQuant.User.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.User.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.User.prototype.toObject = function() { 
    return {
        "user_id" : this.user_id,
        "auth" : this.auth.toObject(),
        "profile" : this.profile.toObject(),
        "permission" : this.permission.toObject(),
        "client" : this.client.toObject(),
        "node" : this.node.toObject(),
        "config" : this.config.toObject(),
        "create" : this.create,
        "update" : this.update
    };
};
ksQuant.User.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "user_id") && (this.user_id = json.user_id);
    _hasOwnProperty.call(json, "auth") && (this.auth.readFromObject(json.auth));
    _hasOwnProperty.call(json, "profile") && (this.profile.readFromObject(json.profile));
    _hasOwnProperty.call(json, "permission") && (this.permission.readFromObject(json.permission));
    _hasOwnProperty.call(json, "client") && (this.client.readFromObject(json.client));
    _hasOwnProperty.call(json, "node") && (this.node.readFromObject(json.node));
    _hasOwnProperty.call(json, "config") && (this.config.readFromObject(json.config));
    _hasOwnProperty.call(json, "create") && (this.create = json.create);
    _hasOwnProperty.call(json, "update") && (this.update = json.update);
    return this;
};
ksQuant.User.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.User.new = function () {
    return new ksQuant.User();
};
ksQuant.User.create = function (is) {
    return ksQuant.User._readFrom(is);
};

ksQuant.UserPack = function() {
    this.is_login = false;
    this.user = new ksQuant.User;
    this._classname = "ksQuant.UserPack";
};
ksQuant.UserPack._classname = "ksQuant.UserPack";
ksQuant.UserPack._write = function (os, tag, value) { os.writeStruct(tag, value); };
ksQuant.UserPack._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
ksQuant.UserPack._readFrom = function (is) {
    var tmp = new ksQuant.UserPack;
    tmp.is_login = is.readBoolean(0, false, false);
    tmp.user = is.readStruct(1, false, ksQuant.User);
    return tmp;
};
ksQuant.UserPack.prototype._writeTo = function (os) {
    os.writeBoolean(0, this.is_login);
    os.writeStruct(1, this.user);
};
ksQuant.UserPack.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
ksQuant.UserPack.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
ksQuant.UserPack.prototype.toObject = function() { 
    return {
        "is_login" : this.is_login,
        "user" : this.user.toObject()
    };
};
ksQuant.UserPack.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "is_login") && (this.is_login = json.is_login);
    _hasOwnProperty.call(json, "user") && (this.user.readFromObject(json.user));
    return this;
};
ksQuant.UserPack.prototype.toBinBuffer = function () {
    var os = new KsfStream.KsfOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
ksQuant.UserPack.new = function () {
    return new ksQuant.UserPack();
};
ksQuant.UserPack.create = function (is) {
    return ksQuant.UserPack._readFrom(is);
};



